### ISSUE TITLE
String() should return error

### ISSUE THREAD

**Issue by bep** [pelletier/go-toml#100]
This is related to #99

I tried to work around this issue by handling the error -- but `String()` doesn't return an error. That would be nice so this could be handled in a cleaner way.

**Comment by moorereason** [comment]
I disagree. `String()` should not return an error.  It would no longer satisfy the `Stringer` interface.  The real problem is that the error should be discovered and returned earlier, as in `TreeFromMap()`.

What we need is `Marshal()` and `Unmarshal()`.

**Comment by bep** [comment]
Call it whatever you want as long as it doesn't panic on common errors.

**Comment by tgulacsi** [comment]
Maybe make it an `encoding.TextMarshaler` (add `MarshalText() ([]byte error)` to TomlTree), or 
maybe even better: add a `WriteTo` method to `TomlTree`?

**Comment by pelletier** [comment]
@tgulacsi just saw your comment. I think adding a `WriteTo` method is the way to go. But I'm not exactly set on the final interface for encoding the tree.

**Comment by tgulacsi** [comment]
See #123 for an example implementation :)
