### ISSUE TITLE
Converting a tree to a string sometimes does not give the expected string

### ISSUE THREAD

**Issue by mike182uk** [pelletier/go-toml#107]
Hey there,

I'm having an issue when converting a map to a tree, then to a string. Using the following example:

```go
package main

import (
	"fmt"
	"strings"
	toml "github.com/pelletier/go-toml"
)

func main(){
	var m1 = map[string]interface{}{
		"foo": 1,
		"bar": "baz",
		"qux": map[string]interface{}{
			"foo": 1,
			"bar": "baz",
		},
		"foobar": true,
	}

	// generate a tree from m1, then convert to a string

	tree := toml.TreeFromMap(m1)
	r := strings.NewReader(tree.ToString())

	// load in the generated toml string

	toml, err := toml.LoadReader(r)

	if err != nil {
		panic(err)
	}

	// convert to a map

	tmap := toml.ToMap()

	// debug

	fmt.Print(tree.ToString())
	fmt.Println(tmap)
}
```

I would expect to get:

```
foo = 1
bar = "baz"

[qux]
  foo = 1
  bar = "baz"

foobar = true
```

```
map[foo:1 bar:baz qux:map[foo:1 bar:baz] foobar:true]
```

But i seem to be getting back the `toml` in a random order, i.e

```
foobar = true
bar = "baz"
foo = 1

[qux]
  foo = 1
  bar = "baz"
```

```
map[foobar:true bar:baz foo:1 qux:map[bar:baz foo:1]]
```

The random order is fine, but every now and again, i get back something like:

```
bar = "baz"

[qux]
  foo = 1
  bar = "baz"
foobar = true
foo = 1
```

```
map[qux:map[foo:1 bar:baz foobar:true] foo:1 bar:baz]
```

When this string is turned back into a tree (and subsequently a map) `foobar` is now incorrectly part of `qux`.

I'm not sure if it's down to how i am using the library or if theres a bug somewhere when converting to a string. Any ideas?

**Comment by pelletier** [comment]
That's definitely a bug. We didn't think about that when we wrote the `ToString` implementation. The [`toTomlValue`](https://github.com/pelletier/go-toml/blob/master/tomltree_conversions.go#L45) needs to be made smarter, and actually care about the orders of the keys, otherwise it ends up in situations you described.

**Comment by pelletier** [comment]
Fixed in https://github.com/pelletier/go-toml/pull/111. Feel free to reopen if it still does not work for you!
