### ISSUE TITLE
Intermittent error when loading in from a reader

### ISSUE THREAD

**Issue by mike182uk** [pelletier/go-toml#108]
Hey,

I came across this when having the problem i reported in #107 

Using the following:

```go
package main

import (
	"fmt"
	"strings"
	toml "github.com/pelletier/go-toml"
)

func main(){
	var m1 = map[string]interface{}{
		"foo": 1,
		"bar": "baz",
		"qux": map[string]interface{}{
			"foo": 1,
			"bar": "baz",
		},
		"foobar": true,
	}

	// generate a tree from m1, then convert to a string

	tree := toml.TreeFromMap(m1)
	r := strings.NewReader(tree.ToString())

	// load in the generated toml string

	toml, err := toml.LoadReader(r)

	if err != nil {
		panic(err)
	}

	// convert to a map

	tmap := toml.ToMap()

	// debug

	fmt.Print(tree.ToString())
	fmt.Println(tmap)
}
```

Most of the time everything would work correctly, but occasionally i would get an error:

```
panic: (6, 1): The following key was defined twice: qux.foo

goroutine 1 [running]:
panic(0xe4160, 0xc42000af20)
        /usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
main.main()
```

Again, i'm not sure if it's down to how i am using the library or if theres something going wrong somewhere else. Any ideas?

**Comment by pelletier** [comment]
Thank you for your feedback! :)

I believe this is exactly https://github.com/pelletier/go-toml/issues/107, as depending on the map's order, `ToString` ends up generating sometimes

```toml
bar = "Baz"
foo = 1
foobar = true
[qux]
foo = 1
bar = "baz"
```

which works, but sometimes

```toml
bar = "Baz"
foobar = true
[qux]
foo = 1
bar = "baz"
foo = 1
```

which would trigger the panic you're seeing.

I'm closing this issue to track the work on https://github.com/pelletier/go-toml/issues/107.
