### ISSUE TITLE
Differing behaviours on Linux and Mac

### ISSUE THREAD

**Issue by pietv** [pelletier/go-toml#112]
I've came across this toml file snippet which produces different results when run on Mac (macOS 10.12.1) and Linux (Debian jessie):

```
package main

import (
	"fmt"
	"os"

	toml "github.com/pelletier/go-toml"
)

func main() {
	toml, err := toml.Load(`
Routes = [
        { Method = "GET", Path="/test" },
        { Method = "GET", Path="/whatever" }
]
`)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Load failed: %v\n", err)
		os.Exit(1)
	}
	config := map[string]interface{}{}
	for key, value := range toml.ToMap() {
		config[key] = value
	}
	fmt.Printf("%#T\n", config["Routes"])
}
```

Mac produces:
```
[]*toml.TomlTree
```
Linux:
```
[]interface {}
```
I very much like them both producing the same result, but just can't quite wrap my head around whether this is a package problem or not (after `Load` they both produce the same result). I hope this might be of interest to you.

**Comment by pelletier** [comment]
This looks like the bug mentioned here https://github.com/pelletier/go-toml/issues/106, which has been fixed. The Linux behavior is the right one, which is also what I get when running your example file on my mac. Do you mind verifying the version of go-toml you're using on your mac?

**Comment by pietv** [comment]
Ok, I'm not sure how i would check that version but after running `go get -u` it produced the same result as on Linux.

**Comment by pietv** [comment]
My issue was about consistency, so i can close this now. Thanks!

**Comment by pelletier** [comment]
You're welcome! Feel free to open another issue if you have any issue / question with the library!
