### ISSUE TITLE
TOML Encoding for slices

### ISSUE THREAD

**Issue by christophermancini** [pelletier/go-toml#114]
I am a Hugo user and we started using your library for TOML encoding / decoding with version .17 of Hugo. I have a website that I have automation tools setup to generate content files and uses sed like functionality to replace or inject values in the TOML frontmatter of the Hugo content file.

The downside is that, our old library encoded slices with both brackets on one line e.g.:

```toml
tags = []
```

and this lib encodes them on separate lines:

```toml
tags = [
]
```

This creates a problem for me as I have thousands of pages with the single line syntax and modifying my code to support the multiline syntax will break the old pages.

Would you be open to allowing me to submit a PR allowing an option to use the single line slice encoding? If so, which file is this specific code executing in because I haven't found it in the ten minutes or so that I was looking.

Thanks.

**Comment by moorereason** [comment]
The code in question is in [tomltree_conversions.go#L81-L86](https://github.com/pelletier/go-toml/blob/7cb988051d5045890cb91402a0b5fddc76c627bc/tomltree_conversions.go#L81-L86).

**Comment by pelletier** [comment]
That PR would be welcomed! :) Providing an option for that is probably overkill. I think it should be the default behavior.

**Comment by christophermancini** [comment]
Created a PR, #119

**Comment by pelletier** [comment]
PR merged, closing.
