### ISSUE TITLE
Consider moving support for queries in its own subpackage

### ISSUE THREAD

**Issue by pelletier** [pelletier/go-toml#116]
I feel like the JSONPath queries is a non-essential part of the project and fairly orthogonal, so it could use to be in it's own package for a cleaner separation.

Today the API works like this:

```go
result, err := tree.Query("$.foo.bar.baz")
```

The new API would look like this:

```go
result, err := query.New("$.foo.bar.baz").exec(tree)
```

**Comment by tgulacsi** [comment]
Good idea!
I chose go-toml just because this nice library. (For my config parser-converter-editor, tgulacsi/confed.)

How would it work? On `map[string]interface{}` or `interface { Keys() []string, Get(string) interface{} }`, or both?

**Comment by pelletier** [comment]
I was thinking something like `interface { Keys() []string, Get(string) interface{} }`, but it may need more methods.

**Comment by pelletier** [comment]
@tgulacsi starting to work on this. for now I think it would require the following interface:

```
type Queryable interface {
    Position() toml.Position
    Keys() []string
    Get(string) interface{}
    GetPosition(string) interface{}
}
```

still a wip and open to suggestions.

**Comment by tgulacsi** [comment]
Are Position/GetPosition required/used somewhere?

**Comment by pelletier** [comment]
As the query code is not in the `toml` package anymore, it can access private fields like `position` on `*TomlTree` and `*tomlValue`. The query exposes the positions alongside the values, which requires the interface to have `GetPosition` and `Position` to retrieve them.

I really wonder how many people actually use positions when using queries. Kinda want to get rid of that.

By the way you can track the progress here: https://github.com/pelletier/go-toml/compare/pelletier/move-query-own-subpackage
