### ISSUE TITLE
Misleading error message in TomlTree.writeTo

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#138]
Given [the following TOML](https://github.com/spf13/hugo/blob/45b9d7223a8098f3c19871ec695c79384bc40871/create/content_test.go#L108) from [this test](https://github.com/spf13/hugo/blob/45b9d7223a8098f3c19871ec695c79384bc40871/create/content_test.go#L46):

```toml
date = "2015-01-12T19:20:04-07:00"
```

The [current implementation of `TomlTree.writeTo`](https://github.com/pelletier/go-toml/blob/13d49d4606eb801b8f01ae542b4afc4c6ee3d84a/tomltree_write.go#L126) returns [a misleading error message](https://travis-ci.org/spf13/hugo/jobs/209152721#L236):

```
invalid key type at date: string
```

I believe the issue is with the value and not the key, and that the error message should be `invalid value type at date: string`.

Related To #137

**Comment by pelletier** [comment]
Good catch! Fixing it in https://github.com/pelletier/go-toml/pull/139/commits/7b2adf05ef40b4bc413ab35bd6da4a598b3f3261
