### ISSUE TITLE
TreeFromMap Fails for Array of Tables

### ISSUE THREAD

**Issue by carolynvs** [pelletier/go-toml#143]
I am using go-toml revision fee7787d3f811af92276f5ff10107092e95b7a1d (the lastest revision on master) and am trying to generate a TOML tree containing an array of tables. When I call `TreeFromMap`, I am getting the error `cannot convert type map[string]interface {} to TomlTree`.

Here's a test which reproduces the error:

```toml
[[stuff]]
name = "foo"
```

```go
func TestRoundTripArrayOfTables(t *testing.T) {
	orig := "\n[[stuff]]\n  name = \"foo\"\n"
	tree, err := Load(orig)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	m := tree.ToMap()

	tree, err = TreeFromMap(m)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	want := orig
	got := tree.String()

	if got != want {
		t.Errorf("want:\n%q\ngot:\n%q", want, got)
	}
}
```

**Comment by carolynvs** [comment]
After playing around with this more, it seems the the real problem is with feeding the result of `ToMap` back into `TreeFromMap`. Is that supported, or am I using those functions incorrectly? I was doing this to learn how to generate a tree programmatically.

**Comment by pelletier** [comment]
Your usage of `ToMap` / `TreeFromMap` is perfectly fine. It seems like there is indeed a bug when it comes to encoding / decoding arrays of tables. I will looking into it when I have a moment, or merge a patch if you find the solution before me :)

**Comment by pelletier** [comment]
@carolynvs https://github.com/pelletier/go-toml/pull/145 should do the trick. Do you mind checking if it works for you please?
