### ISSUE TITLE
Possible test error - PC messages may differ

### ISSUE THREAD

**Issue by tro3** [pelletier/go-toml#147]
@pelletier I am getting the forked project up and running, but I am failing the test suite with one error:

    --- FAIL: TestMissingFile (0.00s)
    parser_test.go:504: Bad error message: open foo.toml: The system cannot find the file specified.

The test appears to expect a message of `"open foo.toml: no such file or directory"`.  By any chance does the test suite assume a Linux build?  (I am running on a PC.)  If so, mind if I `or` the PC message version into the test suite?

**Comment by pelletier** [comment]
I have never tested go-toml on anything else than linux or macos, so there is a chance it does not work on windows. Feel free to adjust the test suite as necessary so that it works on your system. :)

**Comment by tro3** [comment]
PR #148 submitted

**Comment by pelletier** [comment]
Merged. Thanks!
