### ISSUE TITLE
Unmarshal to map

### ISSUE THREAD

**Issue by bogem** [pelletier/go-toml#150]
It will be very useful for https://github.com/nicksnyder/go-i18n/pull/66 to unmarshal TOML to maps, not only to structs.

**Comment by tro3** [comment]
It should be able to marshal/unmarshal a map of string to `<type>` now, where `<type>` is anything but `interface{}`.  Or do you mean at the top level?

**Comment by bogem** [comment]
I just try to execute this code:
```
var v map[string]map[string]interface{}
if err := toml.Unmarshal(tomlData, v); err != nil {
    panic(err)
}
```
And I become an error `Only a pointer to struct can be unmarshaled from TOML`. I looked into Unmarshal func and in https://github.com/pelletier/go-toml/blob/master/marshal.go#L216 I saw, what `v` should be obligatorily pointer to a struct.

**Comment by tro3** [comment]
A top-level of `map[string]T`, where `T` is a specific type, is not too bad to implement.  But `map[string]interface{}` (or `map[string]map[string]interface{}` is not trivial.  I won't have time to attack that for the foreseeable future.

**Comment by pelletier** [comment]
@bogem would the `ToMap()` method be enough in your case? Or do you actually have a more specific structure to map to?

**Comment by bogem** [comment]
Yes, it's enough for me, but we should add some extra code to assert `ToMap()`  to needed map ([like this](https://github.com/nicksnyder/go-i18n/blob/master/i18n/bundle/bundle.go#L92)). It will be more convenient to just pass our map to `Unmarshal` function ([like this](https://github.com/nicksnyder/go-i18n/blob/master/i18n/bundle/bundle.go#L163))

**Comment by pelletier** [comment]
Yes that would make sense. Marking it as a future improvement.

**Comment by pelletier** [comment]
Better late than never! Since #341 got merged, the following test passes:

```go
	tomlData := `
[a]
b = 1
[c]
d = "e"
`

	expected := map[string]map[string]interface{}{
		"a": map[string]interface{}{
			"b": int64(1),
		},
		"c": map[string]interface{}{
			"d": "e",
		},
	}
	
	var v map[string]map[string]interface{}
	if err := Unmarshal([]byte(tomlData), &v); err != nil {
		panic(err)
	}
	if !reflect.DeepEqual(expected, v) {
		t.Errorf("Bad unmarshal: expected %v, got %v", expected, v)
	}
```

I it closes this issue. If the latest master version does not work for you feel free to reopen.
