### ISSUE TITLE
Comments at end of line are removed during roundtrip

### ISSUE THREAD

**Issue by kevinburke** [pelletier/go-toml#156]
If I parse a TOML document into a TomlTree, set a value, and then output the state of the TomlTree, I expect any comments in the original document to be present in the output.

Instead, comments are omitted from the output. This makes machine manipulation of a TOML file more difficult.

The following example illustrates the problem.

```go
package toml

import "testing"

var in = `title = "foo bar" # Comment at end of line`
var want = `title = "different title" # Comment at end of line`

func TestRoundtrip(t *testing.T) {
	tree, err := Load(in)
	if err != nil {
		t.Fatal(err)
	}
	tree.Set("title", "different title")
	out := tree.String()
	if out != want {
		t.Errorf("got %s, want %s", out, want)
	}
}
```

**Comment by pelletier** [comment]
Yes you're right. I think this is part of a broader issue though. Currently, the encoding mechanism does not use the position information, and sorts the keys instead. That would need to be changed in order to be able to preserve comments (otherwise multiline comments wouldn't make sense anymore.

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released, and document manipulation is out of scope for v2. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1). If you believe this is a mistake please reach out!
