### ISSUE TITLE
doco: unclear warning in method Keys()

### ISSUE THREAD

**Issue by client9** [pelletier/go-toml#161]
This a fantastic package, that so much for providing it.

I found this `Warning`, but I'm unclear why this would be "costly".  At one time was it recursive?  Could you provide a bit more color on this?

https://github.com/pelletier/go-toml/blob/master/tomltree_write.go#L190

```
// Keys returns the keys of the toplevel tree.
// Warning: this is a costly operation.
func (t *Tree) Keys() []string {
	keys := make([]string, len(t.values))
	i := 0
	for k := range t.values {
		keys[i] = k
		i++
	}
	return keys
}
```

**Comment by pelletier** [comment]
You are right, this warning is not relevant anymore. At some point this function was supposed to return all keys by recursively traversing the tree, but not anymore.

I'm in the process of updating/rewriting the documentation for the whole project (https://github.com/pelletier/go-toml/issues/135), so I will remove that as part of that effort. If anything else seems unclear / lacks an example or anything, please let me know!
