### ISSUE TITLE
Empty tables in 'Array of Tables' are dropped by tomll

### ISSUE THREAD

**Issue by scooter-dangle** [pelletier/go-toml#163]
It's possible that the `tomll` binary is not meant to be used as a general TOML formatter, but if it is, it should likely not elide empty tables from an [Array of Tables](https://github.com/toml-lang/toml#array-of-tables). Per the spec, I'd expect the following

```toml
# empty-tables.toml
[[empty-tables]]
[[empty-tables]]
```

to be preserved, as is done by `tomljson`:

    > cat empty-tables.toml | tomljson
    {
      "empty-tables": [
        {},
        {}
      ]
    }

When run through `tomll`, though, both entries (and the array itself) are dropped:

    > cat empty-tables.toml | tomll | tomljson
    {}

Is this the intended behavior of `tomll`?

**Comment by pelletier** [comment]
Great catch! That's not expected. As you pointed out, the spec allows for those constructs.
