### ISSUE TITLE
The lexer allocates too much

### ISSUE THREAD

**Issue by bep** [pelletier/go-toml#165]
The TOML lexer lists fairly high on my profiling session in Hugo:

```
         .          .     52:func (l *tomlLexer) next() rune {
         .      10923     53:	r := l.read()
         .          .     54:
         .          .     55:	if r != eof {
   3825735    3825735     56:		l.buffer = append(l.buffer, r)
         .          .     57:	}
         .          .     58:	return r
         .          .     59:}
         .          .     60:
         .          .     61:func (l *tomlLexer) ignore() {
```

The above is allocated objects. I would:

1) Use `bytes.Buffer` (it has a `WriteRune` method).
2) Create a `sync.Pool` for those buffers.

**Comment by bep** [comment]
Not sure if it is related, but I add this here:

https://github.com/spf13/hugo/issues/3541

Not the most specific benchmarks in the world, but just by switching front matter from YAML to TOML adds 50 ms. on the build time in Hugo with 1000 pages with front matter with 1 string field and 20 tags (a list).

**Comment by pelletier** [comment]
Nice! It's about time we start looking at go-toml's performance.
