### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by bep** [pelletier/go-toml#167]
Let us create a more general issue to track this.

See https://github.com/spf13/hugo/issues/3541

That issue shows a significant penalty in just switching from YAML to TOML as front matter in Hugo, both in processing time and memory allocations. I'm not saying it needs to be _as fast_, TOML is a more convenient format, but I think this needs to be looked into.

I think this library needs some simple and isolated benchmarks that compare it to, say, YAML and JSON.

**Comment by pelletier** [comment]
I agree. I haven't paid any attention to performance up until now. There are probably a bunch of low hanging improvements. Do you have some real world example files that we could use for initial benchmarks?

**Comment by bep** [comment]
>Do you have some real world example files that we could use for initial benchmarks?

No.

**Comment by kevinburke** [comment]
For this function:

```go
func encodeTomlString(value string) string {
	result := ""
	for _, rr := range value {
		switch rr {
		case '\b':
			result += "\\b"
		case '\t':
			result += "\\t"
		case '\n':
			result += "\\n"
		case '\f':
			result += "\\f"
		case '\r':
			result += "\\r"
		case '"':
			result += "\\\""
		case '\\':
			result += "\\\\"
		default:
			intRr := uint16(rr)
			if intRr < 0x001F {
				result += fmt.Sprintf("\\u%0.4X", intRr)
			} else {
				result += string(rr)
			}
		}
	}
	return result
}
```

You can probably get a speedup by creating a `map[utf8.RuneSelf]bool` table and checking whether a character exists in the map. If it doesn't you can `continue` early. That would beat the switch statement which forces 7 comparisons before executing the `default` code block.

**Comment by bep** [comment]
What I would do, before starting to make random changes that look like hot spots, is this:

1) Create a couple of benchmarks with a fairly simple, but representable, document -- converted to TOML, YAML and JSON (there are online converters)
2) Run the benchmark and output mem and cpu profiles. Looking at it with `go tool pprof --alloc_objects` is a good start -- memory allocations light up like a Christmas tree, and there is usually a strong correlation from that to speed.
3) Fix the hot spots, repeat until you are within n % of YAML/JSON, or whatever.

**Comment by pelletier** [comment]
Putting https://github.com/spf13/hugo/pull/3545 here for future reference.

**Comment by moorereason** [comment]
Copying a comment @pelletier [made elsewhere](https://github.com/pelletier/go-toml/pull/438#issuecomment-691509873) since it's relevent to this issue:

> As far as memory consumption goes: I think it's a fundamental issue in the way (Un)Marshal was written.
> 
> For unmarshalling, it always builds a Tree first. I think the parser should be changed to accept a "builder" interface, with two implementation: one that builds a Tree, and one that unmarshals directly. Tried to do that [at some point](https://github.com/pelletier/go-toml/tree/unmarshal-rewrite), but not enough time to dedicate to that rewrite at the moment.
> 
> For marshalling, I think building the Tree should also be bypassed. That one is probably less effort because it's mostly a matter of isolating the conversion functions.

**Comment by pelletier** [comment]
Only 4 years later, this should do it :) https://github.com/pelletier/go-toml/discussions/488

**Comment by pelletier** [comment]
https://github.com/pelletier/go-toml/pull/546

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
