### ISSUE TITLE
Floats with zero decimal are converted to integers by tomll and tomljson

### ISSUE THREAD

**Issue by scooter-dangle** [pelletier/go-toml#171]
When a float ends with `.0` (e.g., `3.0`), `tomll` and `tomljson` both convert the float to an integer. This modifies the data and also causes errors when the value in question is in an array with other floats with non-zero decimal components.

Given

```toml
    # single-value.toml
    a = 3.0
```

and

```toml
    # array.toml
    a = [3.0, 3.8]
```

`tomll` and `tomljson` act as follows:

    > cat single-value.toml | tomll
    a = 3

    > cat single-value.toml | tomljson
    {
      "a": 3
    }

    > cat array.toml | tomll
    a = [3,3.8]

    > cat array.toml | tomljson
    {
      "a": [
        3,
        3.8
      ]
    }

    > cat array.toml | tomll | tomljson
    (1, 8): mixed types in array

**Comment by pelletier** [comment]
Got catch! Thank you for the feedback.

**Comment by pelletier** [comment]
This bug should be fixed with the https://github.com/pelletier/go-toml/pull/172. Feel free to reopen if it's not the case!

**Comment by scooter-dangle** [comment]
Looks good...thanks! (Had forgotten that, due to lack of dedicated integer type in JSON, this was really only a problem to be solved in `tomll` and not `tomljson`.)
