### ISSUE TITLE
can't convert  lower case to struct with Unmarshal

### ISSUE THREAD

**Issue by godcong** [pelletier/go-toml#183]
my toml file:
[system]
  version = "0.0.1"
[Wechat]
  Appid = "aaaaaa"
  appsecret = "bbbbbb"
  mchid = "123456"
  redirect_url = ""

my struct def:
type Wechat map[string]string
type System map[string]string
type Config struct {
	System System
	Wechat Wechat
}

question:
unmarshal can't convert [system] with map. [Wechat] is ok.
if modification the toml file:
 [Wechat] => [wechat]
nothing convert

**Comment by moorereason** [comment]
TOML is case sensitive.

**Comment by godcong** [comment]
can it binding with comment like:

type Config struct {
System System `toml:system`
Wechat Wechat `toml:wechat`
}

in go only Upper Case can be transfer...

**Comment by pelletier** [comment]
Yes, you can use the following to unmarshal lowercase fields:

```go
type Config struct {
    System System `toml:"system"`
    Wechat Wechat `toml:"wechat"`
}
```

**Comment by pelletier** [comment]
https://github.com/pelletier/go-toml/pull/189 should clarify that. Feel free to re-open this issue if anything is still unclear.
