### ISSUE TITLE
Apply new version number or update readme to include toml tag

### ISSUE THREAD

**Issue by takayukioda** [pelletier/go-toml#188]
or update readme to use toml tag if current implementation cannot be set as stabled version.

Hi,

I was try using `v1.0.0` of this repository and found that `Unmarshal` method doesn't work by copy & paste of [code sample in README](https://github.com/pelletier/go-toml/blob/v1.0.0/README.md#usage-example) as it is. It requires toml tag to unmarshal correctly like next code.

```go
type Postgres struct {
    User     string `toml:"user"`
    Password string `toml:"password"`
}
type Config struct {
    Postgres Postgres `toml:"postgres"`
}
```

Current master branch seems includes auto-convert feature and works without tag if only the cases were different.

I tried to use `v1.0.0` at first because I was using `dep` for my package manage tool and it gave me `v1.0.0` and I thought it would be stabled version.

I would appreciated if you apply new version number which works without toml tag, or add toml tag definition to readme if current code is not stabled and don't want to apply new version number yet.

In case this report gets old, here's the master branch that I'm looking right now https://github.com/pelletier/go-toml/commit/16398bac157da96aa88f98a2df640c7f32af1da2

**Comment by pelletier** [comment]
You are right I haven't cut a release in a while. I wanted to add more features before doing so but it's taking longer than expected.

So there it is: `1.0.1` https://github.com/pelletier/go-toml/releases/tag/v1.0.1

Let me know if that works for you. Feel free to reopen if you have any issue with it.

**Comment by takayukioda** [comment]
Thanks for quick response! It worked as I expected 👍
