### ISSUE TITLE
Unmarshal example for README doesn't work

### ISSUE THREAD

**Issue by mlcdf** [pelletier/go-toml#191]
Hello!

It seems that the Unsmarshal example from the README doesn't work.

```go
type Postgres struct {
    User     string
    Password string
}
type Config struct {
    Postgres Postgres
}

doc := []byte(`
[postgres]
user = "pelletier"
password = "mypassword"`)

config := Config{}
toml.Unmarshal(doc, &config)
fmt.Println("user=", config.Postgres.User)

```

The `config` object is empty.

It may be because of the case of the struct `Postgres` doesn't match what in the toml (`postgres`).

**Comment by pelletier** [comment]
Good catch. You are right: this is a case issue. Will fix that.

**Comment by mlcdf** [comment]
I can work on fixing and updating this example (if you want).

**Comment by pelletier** [comment]
I won't be able to take a look until this weekend, but I'd be happy to merge your patch before then!

**Comment by pelletier** [comment]
Fixed in https://github.com/pelletier/go-toml/pull/197
