### ISSUE TITLE
Output arrays with one item per line

### ISSUE THREAD

**Issue by pelletier** [pelletier/go-toml#200]
The encoder should be able to emit arrays with one item per line. It would help with diffs, as discussed in https://github.com/golang/dep/issues/789#issuecomment-325197434. Thanks to https://github.com/pelletier/go-toml/pull/192 this can be exposed as an option for the encoder.

**Comment by pelletier** [comment]
cc @carolynvs who may be interested in that :)

**Comment by sdboyer** [comment]
just checking in - any ideas on when you might get round to this? 😄

**Comment by carolynvs** [comment]
Oops, sorry if anyone thought that I was signing up for this issue. I have too much right now to pick this up.

**Comment by pelletier** [comment]
Ha! I actually thought Carolyn was on it. :) I’ll try to squeeze that in next week.

**Comment by pelletier** [comment]
@sdboyer @carolynvs merged the new feature. Let's me know how it goes for you!

**Comment by sdboyer** [comment]
lookin good so far! golang/dep#1461
