### ISSUE TITLE
support for default-value struct tags

### ISSUE THREAD

**Issue by actualben** [pelletier/go-toml#202]
`github.com/koding/multiconfig` is among the config parsing projects that have an interesting feature: you can set a struct tag that defines a default value for unmarshalled structs. 

Here's the example from the multiconfig readme, showing their use of the default tag:

```golang
type Server struct {
	Name    string `required:"true"`
	Port    int    `default:"6060"`
	Enabled bool
	Users   []string
}
```

I think that would be a nice feature to have in go-toml. Do you object to the idea? If not, I could start work on a pull request.

**Comment by pelletier** [comment]
Seems like a good idea to me!

**Comment by chehsunliu** [comment]
Definitely need this enhancement!

**Comment by detailyang** [comment]
+1 plus

**Comment by pelletier** [comment]
This feature should now be available on master. Let me know if you had something else in mind!

**Comment by sourcepark-smatyba** [comment]
For the next person that finds this from a Google search: Support for default values was dropped in v2 (it says so in the README). See #542 for reasons and details. Not complaining, just hoping to save people some time in the future

**Comment by steps0x29a** [comment]
For the next person that finds this from a Google search: Support for default values was dropped in v2 (it says so in the README). See https://github.com/pelletier/go-toml/issues/542 for reasons and details. Not complaining, just hoping to save people some time in the future
