### ISSUE TITLE
Preserving existing comments whilst editing TOML files

### ISSUE THREAD

**Issue by alankm** [pelletier/go-toml#207]
Are there any methods or plans to edit the data in an existing TOML file without destroying existing comments?

**Comment by pelletier** [comment]
There have been some talk about that, but nothing exists at the moment. This would indeed be a nice feature.

**Comment by juan131** [comment]
Hi @pelletier 

Any advance on this feature? It's essential (specially when dealing with configuration files) to preserve the comments since they're fundamental to understand the available parameters.

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released, and document manipulation is out of scope for v2. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1). If you believe this is a mistake please reach out!
