### ISSUE TITLE
commented:"true" doesn't work for non-primitive types

### ISSUE THREAD

**Issue by alankm** [pelletier/go-toml#216]
Using the 'commented:"true"' tag, non-primitive types such as arrays, maps, and structs do not get commented out.

I've had a look around the source code and found that it is not trivial to implement this functionality, but I may be willing to give it a go. Was this behaviour omitted by design?

**Comment by pelletier** [comment]
Good catch, thanks! It is indeed a bug – or likely a part of the implementation that was forgotten. Commenting out a non-primitive type should comment out itself and all the nodes below it.

**Comment by jbsmith7741** [comment]
Just run into this issue when needing to generate a commented slice.
