### ISSUE TITLE
README.md and godocs both use *toml.Tree but the code is using *toml.TomlTree

### ISSUE THREAD

**Issue by willauld** [pelletier/go-toml#218]
Examples in both the README.md and goDocs use *toml.Tree which causes that code to fail to build. Changing this type to *toml.TomlTree allows the build and code to work. 

Thanks,
Will

**Comment by willauld** [comment]
UPDATE: Actually the issus was using the "go get" version which uses TomlTree vs. the "git clone" version which uses Tree. Confusing but...

Thanks,
Will

**Comment by pelletier** [comment]
@willauld do you mind providing the `go get` command you were using? Unless you're specifically referencing a version < 1.0.0 (which renamed `TomlTree` to `Tree`), it should work.

**Comment by willauld** [comment]
I used 'go get github.com/pelletier/go-toml'. 

Then I was using looking at the examples on the repository but they weren't working so I looked at the local code and found TomlTree. Later while looking at the docs I clicked on something that took me to some code and it was using Tree rather than TomlTree and had a comment about having changed this. So, I deleted my local version and did a git clone. 

I don't really understand what "go get" is doing and whether it is any different from "git clone". Sure a different tool but do you need to define things before "go get" will work of is it just "git clone" under the covers?
