### ISSUE TITLE
go-toml panics if unmarshal finds what it thinks is an int while the struct has float64

### ISSUE THREAD

**Issue by willauld** [pelletier/go-toml#219]
The following code panics if the number in the []byte for "percent" is 6 (not 6.0 or 6.5). The go representation must be float because it needs to be able to take on these values. However, users putting data into the file will not be so strict and Toml is much more forgiving. For this reason I think this is a bug. If the field is looking for float unmarshal should convert it as needed. 

func f3() {
	type Person struct {
		Name    string
		Age     int64
		Percent float64
	}

	document := []byte(`
		name = "John"
		age = 30
		percent = 6
		`)

	person := Person{}
	toml.Unmarshal(document, &person)
	fmt.Printf("doc: %#v\n", person)
}

Thanks,
Will

**Comment by pelletier** [comment]
Looks like the patch #236 fixed this issue, closing. Feel free to reopen if it's not the case!
