### ISSUE TITLE
unexpected token type in inline table when using numerical key

### ISSUE THREAD

**Issue by ibrokemypie** [pelletier/go-toml#224]
``
numbers = { 1 = true, 2 = true}
``
When creating an inline table as above, I get the following message
``(10, 18): unexpected token type in inline table: "1"``
however if I change the key name to one or "one" it works fine

**Comment by pelletier** [comment]
Thank you for the bug report! Seems like bare keys starting with a number aren't implemented properly, even though completely legal.

**Comment by ibrokemypie** [comment]
Any plans to fix this issue, or anything I can do to help?

**Comment by pelletier** [comment]
Sorry for the delay. I have given that a shot a couple times. It turns out it is a non-trivial issues, that seems to require a significant amount of untangling in the lexer. I don't have much time to sit down and work on that at the moment, but I would gladly review and merge a patch!
