### ISSUE TITLE
Order in marshalled .toml files

### ISSUE THREAD

**Issue by fho** [pelletier/go-toml#225]
Hello,

is there a way to enforce a certain order when Marshalling a struct to toml?
It seems go-toml is sorting everything alphabetical. This can make the config less intuitive, e.g. when you have section with basic configuration options that should show up first in the config and not somewhere in the middle

**Comment by pelletier** [comment]
There is not at the moment – the alphabetical order was chosen as a way to have reproducible outputs. That can probably be implemented in the form of an option for Marhsal. Patch welcome!

**Comment by pelletier** [comment]
Looks like this is a duplicate of https://github.com/pelletier/go-toml/issues/255, which should be fixed by https://github.com/pelletier/go-toml/pull/266 (available in >= v1.3.0).

@fho could you confirm this is what you were thinking of? Thanks!

**Comment by fho** [comment]
@pelletier yes, https://github.com/pelletier/go-toml/pull/266 implements the feature.
Thanks a lot!
