### ISSUE TITLE
Unable to run test on non English system locale

### ISSUE THREAD

**Issue by sp3c1** [pelletier/go-toml#226]
Some of the tests are based on checking os message - and that can be non English, for example `parser_test.go` in like 617 and 618 when executing `TestMissingFile` would always break.

**Comment by pelletier** [comment]
Good catch! Thank you for the heads up.

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
