### ISSUE TITLE
Allow accidental whitespace between backslash and newline

### ISSUE THREAD

**Issue by pelletier** [pelletier/go-toml#232]
Allow accidental whitespace between backslash and newline in the line
continuation operator in multi-line basic strings.

https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md#string

For writing long strings without introducing extraneous whitespace, use a "line
ending backslash". When the last non-whitespace character on a line is a `\`, it
will be trimmed along with all whitespace (including newlines) up to the next
non-whitespace character or closing delimiter. All of the escape sequences that
are valid for basic strings are also valid for multi-line basic strings.

```toml
# The following strings are byte-for-byte equivalent:
str1 = "The quick brown fox jumps over the lazy dog."

str2 = """
The quick brown \


  fox jumps over \
    the lazy dog."""

str3 = """\
       The quick brown \
       fox jumps over \
       the lazy dog.\
       """
```

**Comment by gdhameeja** [comment]
I can take this up

**Comment by gdhameeja** [comment]
```

			case ' ':
				// skip all whitespace chars following backslash
				for strings.ContainsRune("\r\n\t ", l.peek()) {
					l.next()
				}
```
Doesn't this code in lexer.go take care of this issue?

**Comment by pelletier** [comment]
Confirmed in https://github.com/pelletier/go-toml/pull/319
