### ISSUE TITLE
Keep fields order when Marshaling struct to file

### ISSUE THREAD

**Issue by troian** [pelletier/go-toml#255]
In continue to few comments in #252 
This request might be dupe of #225

Sometimes we need to generate config for user (or just print existing one). There are many purpose for  this. From generating default one to debug, curiosity etc.
Usually config field are grouped to simplify context and when marshaling now all fields gets intermixed.

**Comment by pelletier** [comment]
Thanks for creating this! Not quite a dup of #225, as I think this asks to enforce a specific order, while the present issue is "conserve whatever order there is".

Question: where would you expect a new field to inserted?

**Comment by troian** [comment]
I think there could be an option field specifying order, `OrderPreserve`, `OrderAlphabetical`, `OrderRandom`

If order set to preserve
Old struct
```
type Obj struct {
    Val1 string `toml:"val1" comment:"val1"`
    Val3 string `toml:"val3" comment:"val3"`
}
```
resulting file
```
# val1
val1 = ""

# val3
val3 = ""
```

Update to struct
```
type Obj struct {
    Val1 string `toml:"val1" comment:"val1"`
    Val2 string `toml:"val2" comment:"val2"`
    Val3 string `toml:"val3" comment:"val3"`
}
```

resulting file
```
# val1
val1 = ""

# val2
val2 = ""

# val3
val3 = ""
```

**Comment by pelletier** [comment]
@troian Hi! Just merged a #266. It adds a new `Order` option to the Encoder to preserve order of struct fields when marshaling. Let me know if it solves your issue!

**Comment by troian** [comment]
Cheers, will get back with feedback soon

**Comment by pelletier** [comment]
@troian closing this. Feel free to re-open if you get the chance to try it and it doesn't match your expectations :)
