### ISSUE TITLE
Unmarshal sets missing keys values to zero

### ISSUE THREAD

**Issue by markusheukelom** [pelletier/go-toml#257]
toml.Unmarshal into a struct resets field values to the zero if the blob does not have a key = value pair for that field.

I would expect that toml.Unmarshal only updates the fields for the key = value it encounters.

NOTE: I am uncertain if this is by design, the documentation does not mention this. But if so, I am missing an obvious way to  use default values for keys in a toml file?

**Comment by pelletier** [comment]
Yep, it's known issue: https://github.com/pelletier/go-toml/issues/252

The tl;dr: 

> The root cause is that when unmarshalling, [the whole object is replaced](https://github.com/pelletier/go-toml/blob/master/marshal.go#L462.), instead of being merged. My long-term plan to rewrite the parser inside-out to build the unmarshalled result as it runs would fix it, but just can't find the time to work on it.
> 
> In the meantime, one option would be to turn that `Set` operation into a merge operation when processing structs and maps. Not elegant but should get the job done.

I personally don't have the time to work on it at the moment, but a patch is welcomed!
