### ISSUE TITLE
Support Toml 5.0

### ISSUE THREAD

**Issue by awkj** [pelletier/go-toml#263]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
TOML 5.0 have pre-release ,Can support it ?
https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md

**Comment by pelletier** [comment]
There is a [milestone tracking TOML 0.5.0 support](https://github.com/pelletier/go-toml/milestone/4). There are 3 missing features remaining at this moment. If you've seen any other gap between the current implementation and the 0.5.0 spec let me know!

**Comment by awkj** [comment]
> There is a [milestone tracking TOML 0.5.0 support](https://github.com/pelletier/go-toml/milestone/4). There are 3 missing features remaining at this moment. If you've seen any other gap between the current implementation and the 0.5.0 spec let me know!

ok, so I close this issue, if I find , I try to open it agin.
