### ISSUE TITLE
TestDocMarshalOrdered is flaky

### ISSUE THREAD

**Issue by pelletier** [pelletier/go-toml#268]
**Describe the bug**

TestDocMarshalOrdered is flaky on both Travis and Circle. 

https://circleci.com/gh/pelletier/go-toml/121

**To Reproduce**

Wait for that test to fail. Re-run once or twice. Watch it pass. Or use

```
while go test github.com/pelletier/go-toml -count=1; do echo ok; done;
```

**Expected behavior**

Tests should not be flaky. They should be deterministic and pass

**Versions**
 - go-toml: 2fc2b602876e7e559877fb6ab5357a812ba04eb8
 - go: 1.11
 - operating system: Linux

**Additional context**

Might just be luck, but only seen it fail on 1.11, not 1.12.

**Comment by pelletier** [comment]
@brendesp FYI. May be related to https://github.com/pelletier/go-toml/pull/266.

**Comment by pelletier** [comment]
Seems like it's because there is no guaranteed order in preserve mode for maps. Because of

https://github.com/pelletier/go-toml/blob/d95bfe020e0c72df368b4368a4bf61d95eb4416c/marshal.go#L332

The `Tree` created from a map can result having keys in any order. Marshaling them becomes nondeterministic. Because the test performs byte-wise comparison with the expected output, it becomes flaky.

Two ways to solve the problem. Either enforce alphabetical orders when marshaling maps. Or change the test so that it does not assert order on maps.

**Comment by brendesp** [comment]
I like alphabetically ordering the maps.  I should be able to get back to this later in the week.
