### ISSUE TITLE
Add UnmarshalSkipDefault/SetDefaults

### ISSUE THREAD

**Issue by rekby** [pelletier/go-toml#275]
I want merge few config files in one config value (for example few files in config folder).

I suggest add toml.UnmarshalSkipDefault([]byte, interface{}) method.

May be syntax sugar: SetDefaults (for use instead of unmarshal empty bytes)

Example:
```golang
package main

import (
	"fmt"

	"github.com/pelletier/go-toml"
)

type configType struct {
	V1 int `default:"123"`
	V2 int `default:"456"`
}

func main() {
	var config configType
	err := toml.Unmarshal([]byte(""), &config) // << SetDefaults

	err = toml.Unmarshal([]byte("V1=222"), &config) // << UnmarshalSkipDefault
	if err != nil {
		panic(err)
	}

	err = toml.Unmarshal([]byte("V2=333"), &config) // << UnmarshalSkipDefault

	if err != nil {
		panic(err)
	}
	result, err := toml.Marshal(&config)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(result))
}
```

Output:
```
V1 = 123
V2 = 333
```

Expected output:
```
V1 = 222
V2 = 333
```

**Comment by pelletier** [comment]
Thanks for the feedback! This looks like a good candidate for an option on the decoder:

```go
type configType struct {
	V1 int `default:"123"`
	V2 int `default:"456"`
}

result := configType{}
err := NewDecoder(buf).UseDefaults(false).Decode(&result)
```

**Comment by rekby** [comment]
Yes, decoder option will better, then special method.

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released, v2 does not support defaults. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1). If you believe this is a mistake please reach out!
