### ISSUE TITLE
Add Option to make Unmarshal() return an error if parsed data contains unprocessed keys

### ISSUE THREAD

**Issue by fho** [pelletier/go-toml#277]
Currently it's impossible to handle when a toml configuration file contains a typo in the name of an optional key.
I can't check if the value in the unmarshalled struct is empty because it's an optional field.
An empty value is valid.

Suggestion:
Add an option for the `go-toml` `Encoder`, that if enabled makes `Unmarshal()` return an error when the passed `data` contains keys that were not unmarshalled into any fields of the passed struct.

**Comment by pelletier** [comment]
Sounds good to me! Thank you. Do you happen to know of any other Go encoding/decoding libs that support that feature? If there are existing "standards" for this feature, would love to follow them to match expectations / lower surprises.

**Comment by fho** [comment]
@pelletier no, sorry I don't know how other decoders solve it

**Comment by lmb** [comment]
https://godoc.org/github.com/naoina/toml has an option `MissingField func(typ reflect.Type, key string) error` which is called when no match is found.

`github.com/BurntSushi/toml` allows accessing undecoded fields after decoding: https://godoc.org/github.com/BurntSushi/toml#ex-package--StrictDecoding

Both work, I think the function is nicer.
