### ISSUE TITLE
Default for slices

### ISSUE THREAD

**Issue by rekby** [pelletier/go-toml#278]
**Is your feature request related to a problem? Please describe.**
I have config for listeners, it can contain few addresses (strings). It has default value - for bind one well-known address (https port). Now I can't set default value from "default" comment.

**Describe the solution you'd like**
Add support slice []string (and may be other types) for tag default

**Describe alternatives you've considered**
Now I set default value in own handler. It is more bad for support and bugs.

**Comment by pelletier** [comment]
Hi! Thanks for sharing your use case. Do you have an example of how you'd like the tag to be written, with the expected results? Asking to make sure we are on the same page.

**Comment by rekby** [comment]
for example - as JSON array/object.

type S struct {
  V []string `default:"['aaa', 'bbb']"`
}

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released, and v2 does not support defaults. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1). If you believe this is a mistake please reach out!
