### ISSUE TITLE
Unexpected behavior of decoding to nested anonym struct

### ISSUE THREAD

**Issue by kamilsk** [pelletier/go-toml#279]
**Describe the bug**
I tried to extend some struct to parse full toml-file and return just part of it.

**To Reproduce**
```toml
some = "value X"
another = "value Y"
```

```go
type A struct {
	Some string `toml:"some"`
}

type B struct {
	A
	Another string `toml:"another"`
}

var b B
toml.NewDecoder(r).Decode(&cnf)
fmt.Println(b)
```

**Expected behavior**
```
{{value X} value Y}
```
For example the `encoding/json` behavior: https://play.golang.org/p/x8kaSVpuqh3

**Versions**
 - go-toml: v1.3.0
 - go: 1.11.5
 - operating system: macOS

**Additional context**
Where it's happening: https://github.com/kamilsk/lift/blob/2a8adcf60311d217be784f172699d83a2031f48d/internal/config/app.go#L69-L77
TOML file: https://github.com/kamilsk/lift/blob/2a8adcf60311d217be784f172699d83a2031f48d/testdata/app.toml

**Comment by kamilsk** [comment]
I improved example https://play.golang.org/p/2EXYzlC522l

**Comment by pelletier** [comment]
Good catch! Thanks for the bug report. Didn't even know extending structs like that was possible 😶
