### ISSUE TITLE
Inline table keys not fully supported

### ISSUE THREAD

**Issue by 2shortplanks** [pelletier/go-toml#282]
**Describe the bug**

According to the [spec](https://github.com/toml-lang/toml/blob/v0.5.0/versions/en/toml-v0.5.0.md#user-content-inline-table) in an inline table:
>  Key/value pairs take the same form as key/value pairs in standard tables

However, this library complains on anything other than something starting with a literal A-Z-a-z

**To Reproduce**

```
$ echo 'foo = { -bar => "buz"}' | ./tomljson
(1, 9): unexpected token type in inline table: Error
$ echo 'foo = { "whatever" = "buz"}' | ./tomljson
(1, 10): unexpected token type in inline table: String
echo 'foo = { _no = "buz"}' | ./tomljson
(1, 9): unexpected token type in inline table: Error
```

**Expected behavior**

```
$ echo 'foo = { -bar = "buz"}' | ./tomljson
{
  "foo": {
    "bar": "buz"
  }
}
$ echo 'foo = { "whatever" = "buz"}' | ./tomljson
{
  "foo": {
    "whatever": "buz"
  }
}
$ echo 'foo = { _no = "buz"}' | ./tomljson
{
  "foo": {
    "_no": "buz"
  }
}
```

**Versions**

```
mark@vagrant-mark:~/go/src/github.com/pelletier/go-toml/cmd/tomljson [master] $
728039f679cbcd4f6a54e080d2219a4c4928c546
mark@vagrant-mark:~/go/src/github.com/pelletier/go-toml/cmd/tomljson [master] $ go version
go version go1.11.5 linux/amd64
```

**Additional context**

Nope

**Comment by pelletier** [comment]
Good catch! Thank you.

**Comment by jonathanlloyd** [comment]
I'd like to have a go at this is that's OK :smile:

**Comment by pelletier** [comment]
Please! Feel free to open a draft PR if you’d like early feedback too. Thank you for your interest in go-toml :)
