### ISSUE TITLE
toml.Unmarshal overrides origin values even if not export field

### ISSUE THREAD

**Issue by For-ACGN** [pelletier/go-toml#283]
**Describe the bug**
toml.Unmarshal overrides origin values even if not export field

**To Reproduce**
``````go
package main

import (
	"fmt"
	"log"

	"github.com/pelletier/go-toml"
)

type Ti interface {
	Print()
}

type tii struct {
	A string
}

func (this *tii) Print() {
	fmt.Print(this.A)
}

type S struct {
	A  string
	ti Ti
	tp *tii
}

func main() {
	ti := new(tii)
	tp := new(tii)
	s := &S{A: "asd", ti: ti, tp: tp}
	b, err := toml.Marshal(s)
	if err != nil {
		log.Fatalln(err)
	}
	fmt.Printf("%p %p %p \n", &s.A, s.ti, s.tp)
	toml.Unmarshal(b, s)
	fmt.Printf("%p %p %p \n", &s.A, s.ti, s.tp)
	ti.Print()
	tp.Print()
	s.ti.Print()
	s.tp.Print()
}
``````
print
``````
0xc0000884e0 0xc00005e4c0 0xc00005e4d0
0xc0000884e0 %!p(<nil>) 0x0
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x4eea54]

goroutine 1 [running]:
main.main()
        E:/Project/toml bug/toml.go:41 +0x4a4
exit status 2

``````

**Expected behavior**
not set nil

**Versions**
 - go-toml: v1.4.0 and https://github.com/pelletier/go-toml/commit/dba45d427ff48cfb9bcf633db3a8e43b7364e261
 - go: version 1.12.5
 - operating system: Windows

**Comment by pelletier** [comment]
Thanks for the bug report! Looks like #284 will fix that problem as soon as it's merged (it does work for this specific example).

**Comment by pelletier** [comment]
@For-ACGN https://github.com/pelletier/go-toml/pull/284 has been merged. Do you mind giving this another shot to make sure the bug is fixed for you?

**Comment by For-ACGN** [comment]
@pelletier @roberth-k 
Oh! It fix this bug and works right. Thank you! 
[https://github.com/For-ACGN/go-toml-test](url)
