### ISSUE TITLE
Array in slice silently ignored 

### ISSUE THREAD

**Issue by xiegeo** [pelletier/go-toml#285]
**Describe the bug**
```
type foo struct {
	AB []int
	XY [2]int
}

type bar struct {
	AB  []int
	XYs [][2]int
}
```
When attempting to encode a foo, the error `Marshal can't handle [2]int(array)` is returned. But when encoding a bar, data in XYs is missing from the result without any error reported.

**To Reproduce**
https://play.golang.org/p/JGjdrcJiBMT

**Expected behavior**
Encoding completes without missing data, or error is returned.

**Versions**
 - go-toml: v1.4.0
 - go: go1.12.6 windows/amd64
 - operating system: Windows 10

**Comment by pelletier** [comment]
Thank you for the bug report! I think the right course of action is add array support to the marshal function.
