### ISSUE TITLE
Crash in Fuzz()

### ISSUE THREAD

**Issue by kjk** [pelletier/go-toml#287]
I was experimenting with adding continuous fuzzing integration with https://fuzzit.dev and I found this crash in the fuzzer:

```
FUZZER: #1085900	REDUCE ft: 19023 corp: 1838/457Kb lim: 724 exec/s: 4505 rss: 43Mb L: 96/4817 MS: 1 EraseBytes-
FUZZER: panic: unsupported value type *toml.Tree: 
FUZZER: 
FUZZER: goroutine 17 [running, locked to thread]:
FUZZER: github.com/pelletier/go-toml.Fuzz(0x3c1d340, 0x8, 0x8, 0xc0001e2700)
FUZZER: 	/home/travis/gopath/src/github.com/pelletier/go-toml/fuzz.go:19 +0x2f9
FUZZER: main.LLVMFuzzerTestOneInput(0x3c1d340, 0x8, 0x872248)
FUZZER: 	/tmp/go-fuzz-build054189183/gopath/src/github.com/pelletier/go-toml/go.fuzz.main/main.go:35 +0x66
FUZZER: main._cgoexpwrap_7fe1307e28be_LLVMFuzzerTestOneInput(0x3c1d340, 0x8, 0x9449e0)
FUZZER: 	_cgo_gotypes.go:64 +0x37
FUZZER: ==2== ERROR: libFuzzer: deadly signal

FUZZER:     #0 0x4b042f in __sanitizer_print_stack_trace /tmp/final/llvm.src/projects/compiler-rt/lib/ubsan/ubsan_diag_standalone.cc:29:3
FUZZER:     #1 0x452838 in fuzzer::PrintStackTrace() /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:206:5
FUZZER:     #2 0x430b1b in fuzzer::Fuzzer::CrashCallback() /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:237:3
FUZZER:     #3 0x430adf in fuzzer::Fuzzer::StaticCrashSignalCallback() /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:209:6
FUZZER:     #4 0x7fce9916b0df  (/lib/x86_64-linux-gnu/libpthread.so.0+0x110df)
FUZZER:     #5 0x504a00 in runtime.raise /tmp/go-fuzz-build054189183/goroot/src/runtime/sys_linux_amd64.s:149
FUZZER: 
FUZZER: NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 1 EraseBytes-; base unit: d9ada8a50f4611a456a4d7c9ebe70c0a1b756da1
0x79,0x3d,0x5b,0x5b,0x7b,0x7d,0x5d,0x5d,
y=[[{}]]
artifact_prefix='./'; Test unit written to ./artifact
Base64: eT1bW3t9XV0=
stat::number_of_executed_units: 1099056
stat::average_exec_per_sec:     4485
stat::new_units_added:          130
stat::slowest_unit_time_sec:    0
stat::peak_rss_mb:              46
INFO:root:fuzzer exited with 76
INFO:root:Uploading crash...
INFO:root:fuzzing completed
```

The crashing input to `Fuzz` function is: `y=[[{}]]` (which is `eT1bW3t9XV0=` after base64 decoding).

It's unclear to me if that's the bug in the code or over-eager panic in `Fuzz`. The code is:
```
func Fuzz(data []byte) int {
	tree, err := LoadBytes(data)
	if err != nil {
		if tree != nil {
			panic("tree must be nil if there is an error")
		}
		return 0
	}

	str, err := tree.ToTomlString()
	if err != nil {
		if str != "" {
			panic(`str must be "" if there is an error`)
		}
		panic(err)
	}
```

So `tree.ToTomlString()` returns an error and `Fuzz` function panics because of that.

I guess the assumption is that if `LoadBytes()` doesn't return an error then `ToTomlString()` shouldn't either.

If the assumption is not correct, then `panic(err)` should be converted into `return 0`.

If the assumption is correct, then either `LoadBytes()` should return an error for this input or `ToTomlString()` should handle it.

This is with latest go and master of go-toml.

**Comment by pelletier** [comment]
Good catch! It looks like a bug in LoadBytes. `[[{}]]` would mean an array of tables that has the name `{}`. Given table names should follow the same rules as keys, this is a bare key. In a bare key, only `A-Za-z0-9_-` is allowed.  It should return an error.

I didn't know about fuzzit.dev. Definitely open to setting it up on go-toml if they are free for open source.

**Comment by kjk** [comment]
Yes, fuzzit.dev is free for open source projects.

**Comment by pelletier** [comment]
Just re-read my explanation of it. I missed the `y=` part of the input.

The input is valid, and go-toml should not not crash.

It represents a key `y` assigned to an array of array of empty inline tables. The equivalent JSON would be like

```json
{
  "y": [
    []
  ]
}
```

**Comment by WilliamHeaven** [comment]
@kjk 
I am working on writing a fuzz test, but I am prompted on the fuzzit platform that there is no corpus, can you tell me what should I do? Or is there any relevant fuzz test case design information for my reference? Thank you

**Comment by pelletier** [comment]
After almost two years, this has been fixed in the upcoming v2 https://github.com/pelletier/go-toml/commit/f2378983d915155440efd2ce5168df779ff48c2b!

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
