### ISSUE TITLE
Float64 trucating

### ISSUE THREAD

**Issue by ProfessorMc** [pelletier/go-toml#289]
**Describe the bug**
Float64 values are truncated to float 32 on Marshaling.

**To Reproduce**
Serialize a float 64 with enough precision.
ex. 
// value with too much precision for float 32
val float64 = 1.24675324675
//outputs after marshal (float 32 value)
1.2467532

**Expected behavior**
Should honor float 64 precision.

**Versions**
latest

**Additional context**
tomlValueStringRepresentation is the culprit, it does a float parse to 32 bit.  I tweaked it, but that adds resolution errors to the 32 bit tests, so figured I'd fill a report.  Let me know if this is by design, I'm assuming it isn't.

**Comment by pelletier** [comment]
Thanks for the report! Definitely a bug.
