### ISSUE TITLE
tree.Marshal() returns empty bytes without any errors

### ISSUE THREAD

**Issue by yukithm** [pelletier/go-toml#295]
**Describe the bug**
`tree.Marshal()` returns empty bytes without any errors.

**To Reproduce**
```go
package main

import (
	"fmt"
	"os"

	"github.com/pelletier/go-toml"
)

func main() {
	data := map[string]interface{}{
		"section": map[string]string{
			"name": "foo",
		},
	}

	tree, err := toml.TreeFromMap(data)
	if err != nil {
		panic(err)
	}

	fmt.Println(tree.Marshal()) //=> [] <nil>

	fmt.Println(tree.String())       // worked perfectly
	fmt.Println(tree.ToTomlString()) // worked perfectly
	tree.WriteTo(os.Stdout)          // worked perfectly
}
```

**Expected behavior**
It returns TOML content.

```
[section]
  name = "foo"
```

**Versions**
 - go-toml: v1.4.1-0.20190827035702-3ded2e09ee1b
 - go: go1.12.9 darwin/amd64
 - operating system: macOS

**Comment by pelletier** [comment]
Thanks for the bug report! That definitely looks wrong.

**Comment by mbialon** [comment]
I don't understand why the `Marshal` method tries to process the `Tree` struct. The struct doesn't have exported fields so `Marshal` returns an empty result.

```go
func (t *Tree) Marshal() ([]byte, error) {
	var buf bytes.Buffer
	err := NewEncoder(&buf).Encode(t)
	return buf.Bytes(), err
}
```

What do you think about replacing the encoding part with a calling `WriteTo`, similarly to `ToTomlString`?

```go
func (t *Tree) Marshal() ([]byte, error) {
	var buf bytes.Buffer
	_, err := t.WriteTo(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
```

**Comment by pelletier** [comment]
That makes sense. Looks like `Tree.Marshal()` should just call `ToTomlString` and cast to bytes.

This is the kind of function that I regret having published. There are 4 ways to emit a TOML document:

* `Tree.ToTomlString()`
* `Tree.Marshal()`
* `Marshal()`
* `Encoder.Encode()`

The last two are here to mirror the standard `json` library. The first two serve the same purpose (turn a tree into a TOML string/bytes). Clearly there should be just one.
