### ISSUE TITLE
Fuzzit.dev breaks on pull requests

### ISSUE THREAD

**Issue by pelletier** [pelletier/go-toml#299]
**Describe the bug**
Fuzzit.dev crashes with

```
No such directory: seed_dir/empty; exiting
```

in pull requests.

**To Reproduce**
Open any pull request.

**Expected behavior**
Fuzzit.dev should run successfully on pull requests, and only break on regressions.

**Additional context**
* Fuzzit.dev added here: https://github.com/pelletier/go-toml/pull/288
* Switched from Travis to Github Actions here:  https://github.com/pelletier/go-toml/pull/294

**Comment by pelletier** [comment]
@yevgenypats seems to me fuzzit.dev is acting up. Mind taking a look?

**Comment by yevgenypats** [comment]
hey @pelletier can you try updating CLI to latest version (v2.4.52) https://github.com/fuzzitdev/fuzzit/releases/tag/v2.4.52

**Comment by pelletier** [comment]
Looks it did the trick. Thanks!

**Comment by yevgenypats** [comment]
Sure!
