### ISSUE TITLE
Better support of lists

### ISSUE THREAD

**Issue by hupfdule** [pelletier/go-toml#323]
**Is your feature request related to a problem? Please describe.**
A very frequent use case in TOML is using a list of strings:

```toml
my_list = [ "one", "two" ]
```

Of course in go code this would likely be handled as a slice of strings:

```go
var myList = []string
```

**Describe the solution you'd like**
For this standard use case I would expect I could write something like

```go
config, err := toml.Load("a = [ 'one', 'two' ]")
if err != nil {
	log.Fatal(err)
}

myList = config.Get("my_list").([]string)
```

**Describe alternatives you've considered**
After struggling with go complaining about `interface conversion: interface {} is []interface {}, not []string` and finally having found #33 I realized that `go-toml` doesn't support this since TOML allow multiple different types in the same array (which actually is a very strange idea).

However having to write

```go
tmp := config.Get("my_list").([]interface{})
myList = make([]string, len(tmp))
for i := range tmp {
  myList[i] = tmp[i].(string)
}
```

seems very cumbersome to me.
As in nearly all cases an array in TOML will contain only contain values of the same type, I would expect direct support for these types (mainly []string, but also other default types) to be directly accessible without that boilerplate above.

**Additional context**
An example code snippet in the [Go Playground](https://play.golang.org/p/SFccJVomfAy)

**Comment by pelletier** [comment]
Sorry it took a while to get back to you.

Interesting idea. At some point I seriously considered not supporting TOML's mixed types arrays. One of the reasons why I initially did not want to introduce specialized functions to deal with this was to avoid having the size of the library's interface blow up.

For this example, do you think `Unmarshal` would be good enough?

For example:

https://play.golang.org/p/vMS55PjCFBZ

```go
package main

import (
	"fmt"
	"github.com/pelletier/go-toml"
	"log"
)

var myList []string

func main() {
	tomlDoc := []byte(`my_list = [ 'one', 'two' ]`)
	
	type doc struct {
		MyList []string `toml:"my_list"`
	}
	
	var d doc
	
	err := toml.Unmarshal(tomlDoc, &d)
	if err != nil {
		log.Fatal(err)

	}

	fmt.Println(d.MyList)
}
```
outputs:
```
[one two]
```

**Comment by hupfdule** [comment]
> Sorry it took a while to get back to you.
> 
> Interesting idea. At some point I seriously considered not supporting TOML's mixed types arrays. One of the reasons why I initially did not want to introduce specialized functions to deal with this was to avoid having the size of the library's interface blow up.
> 
> For this example, do you think `Unmarshal` would be good enough?
> 
> For example:
> 
> https://play.golang.org/p/vMS55PjCFBZ
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"github.com/pelletier/go-toml"
> 	"log"
> )
> 
> var myList []string
> 
> func main() {
> 	tomlDoc := []byte(`my_list = [ 'one', 'two' ]`)
> 	
> 	type doc struct {
> 		MyList []string `toml:"my_list"`
> 	}
> 	
> 	var d doc
> 	
> 	err := toml.Unmarshal(tomlDoc, &d)
> 	if err != nil {
> 		log.Fatal(err)
> 
> 	}
> 
> 	fmt.Println(d.MyList)
> }
> ```
> 
> outputs:
> 
> ```
> [one two]
> ```

**Comment by pelletier** [comment]
> If I am not mistaken (and I may very well be mistaken) you either use Unmarshal or walk the tree structure. It is not possible to combine both approaches.¹

Correct. Just wanted to make sure you knew of that option, in the off-chance it would unblock you. :)

What do you think of the following:

add a new `GetArray()` method on `*Tree`. It would work similar to `Get`. It would still return an `{}interface`. But it would actually return `[]string`, `[]int64`, etc. in case all the elements of the array are of the same type. It would return `[]interface{}` if the array contains mixed values or structs.

Thoughts?

**Comment by hupfdule** [comment]
Sorry, I just realized that I missed your comment.

I am not sure I fully understand all consequences, but your proposal seems to be a good idea. It would allow for much more readable code in case of homogenous lists and still allows heterogenous lists.
