### ISSUE TITLE
Do not Bulid.

### ISSUE THREAD

**Issue by keito940** [pelletier/go-toml#325]
**Describe the bug**
```
C:\Users\keito940>go get https://github.com/pelletier/go-toml
package https:/github.com/pelletier/go-toml: https:/github.com/pelletier/go-toml: invalid import path: malformed import path "https:/github.com/pelletier/go-toml": invalid char ':'
```

**To Reproduce**
Steps to reproduce the behavior. Including TOML files.

**Expected behavior**
A clear and concise description of what you expected to happen, if other than "should work".

**Versions**
 - go: version 1.13.4
 - operating system: Windows

**Additional context**
Add any other context about the problem here that you think may help to diagnose.

**Comment by pelletier** [comment]
Hi! Thank you for your interest in go-toml.

I believe the right command to install go-toml with `go get` would be

```
go get github.com/pelletier/go-toml
```

(without the `https://`)

Do you mind trying it to see if it works?

**Comment by pelletier** [comment]
Closing. Feel free to reopen if you still have an issue.
