### ISSUE TITLE
allow custom struct unmarshal with UnmarshalText

### ISSUE THREAD

**Issue by billryan** [pelletier/go-toml#329]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to support my struct, e.g. custom struct.

**Describe the solution you'd like**
Use `encoding.TextUnmarshaler`, we can implement `UnmarshalText`.

**Describe alternatives you've considered**
Universal unmarshal solutions.

**Additional context**
[BurntSushi/toml](https://github.com/BurntSushi/toml#using-the-encodingtextunmarshaler-interface)

**Comment by pelletier** [comment]
Thanks! Being more in-line with existing patterns would be a good thing.
