### ISSUE TITLE
How to read toml into string arrays?

### ISSUE THREAD

**Issue by loongmxbt** [pelletier/go-toml#33]
For example, I have two string arrays: var Langs, Names []string .
The toml file looks like this:
[i18n]
langs = ["en-US", "de-DE"]
names = ["English", "Deutsch"]
What is the proper/direct/intuitive way to load data into string arrays? Thanks a lot!

**Comment by pelletier** [comment]
```go
package main

import (
	"fmt"
	"github.com/pelletier/go-toml"
)

func main() {
	data := `[i18n]
langs = ["en-US", "de-DE"]
names = ["English", "Deutsch"]`
	tree, _ := toml.Load(data) // or LoadFile
	// version 1
	langs := tree.Get("i18n.langs").([]interface{})
	names := tree.Get("i18n.names").([]interface{})
	fmt.Println(langs[1], names[1])
	// version 2
	langsInter := tree.Get("i18n.langs").([]interface{})
	namesInter := tree.Get("i18n.names").([]interface{})
	langs2 := make([]string, len(langsInter))
	names2 := make([]string, len(langsInter))
	for i := range langsInter {
		langs2[i] = langsInter[i].(string)
		names2[i] = namesInter[i].(string)
	}
	fmt.Println(langs2[1], names2[1])
}
```

Because TOML allows arrays to contain elements of multiple types, go-toml returns an `[]interface{}` when you fetch an array. The first version does just that. The second one also casts to a `[]string`, if you actually need that type.

**Comment by pelletier** [comment]
@loongmxbt does it answer your question?

**Comment by loongmxbt** [comment]
@pelletier Yeah! Thank you very much! The essence is the `[]interface{}` and slice item type conversion. I didn't do it right coz I think I can do type conversion directly to the slice, not using for each. I think I need to learn more Golang basics.
