### ISSUE TITLE
Support unmarshal nested interface type

### ISSUE THREAD

**Issue by jinleiw** [pelletier/go-toml#331]
I think it's better to support nested Interface, For example:
```
type Conf struct {
     IntVal int
     InterVal interface{}
}

type NestedStruct struct {
    Name string
    Age int
}
var config Conf

config.InterVal = &NestedStruct{}

decoder.decode(&config)
```

**Comment by pelletier** [comment]
Nested structs should be supported. Do you mind trying with name and age as public attributes (capitalized names)?

**Comment by jinleiw** [comment]
Sorry, spelling mistakes. Yes, they are public attributes:

```
type NestedStruct struct {
    Name string
    Age int
}
```

**Comment by jinleiw** [comment]
Could you help me review the commit “75121fd”, if ok, then I open up a pull request. Thanks
