### ISSUE TITLE
Unexpected result when nested struct

### ISSUE THREAD

**Issue by jinleiw** [pelletier/go-toml#339]
**Describe the bug**
For nested struct，if there are attributes with same name, parse result is not expected.

**To Reproduce**
```
type Server struct {
    Name string `toml:"name" default:"noname"`
    Inter2 Inter2 `toml:"inter2"`
}

type Inter2 struct {
    Name         string
    Age          int
    InterStruct2 InterStruct2
}

type InterStruct2 struct {
    Test string
    Name string
    Age  int
}
var server Server

err := toml.Unmarshal([]byte(`name = "123"

[inter2]
	name = "inter2"
	age = 222`), &server)
```

**Expected behavior**
Expected value of server:
```
{Name:"123", Inter2:{Name:"inter2", Age:222, InterStruct2:{Test:"", Name:"", Age:0}}}
```

but got:
```
{Name:"123", Inter2:{Name:"inter2", Age:222, InterStruct2:{Test:"", Name:"inter2", Age:222}}}
```

**Versions**
 - go-toml: master
 - go: 1.13.8
 - operating system: Windows

**Comment by pelletier** [comment]
@jinleiw Thank you for your bug report! Just merged @AllenX2018's patch, which should have fixed the problem. If you are still experiencing the issue with the latest master code, feel free to reopen this issue!
