### ISSUE TITLE
Add compiled binaries to releases

### ISSUE THREAD

**Issue by josegonzalez** [pelletier/go-toml#342]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to use the `tomljson` binary in a heroku buildpack to parse toml files from a Julia project. At the moment, I need to install Golang and then manually compile `tomljson`, which adds extra time to my app deploy.

**Describe the solution you'd like**

It would be great if each release on github also had the built binaries (for Darwin and Linux) attached to them, that way I could download the binary as necessary.

**Describe alternatives you've considered**

The alternative is to manually build and compile these, but having them with the release would be a nice way for others to ensure they aren't getting lord-knows-what from my buildpack. In essence, we are trusting you, as the library developer, to build the right thing :)

**Comment by pelletier** [comment]
Good idea! I will look into attaching the ones tested by CI to releases.

**Comment by josegonzalez** [comment]
Could be good to attach a checksum to the CI output, and then include that checksum in the release notes/attachment to the release. Would be another way to verify that the bin is the correct one :)

**Comment by pelletier** [comment]
@josegonzalez here is an example of the binaries (+sha256sum) attached to the on-going `master` release: https://github.com/pelletier/go-toml/releases/tag/master. Does that work for you?

**Comment by josegonzalez** [comment]
Would it be possible to also include the sha256sums in the release text? Just one more avenue of verification :)

**Comment by pelletier** [comment]
You mean in the release description as opposed to a separate file like it is in that one?

**Comment by josegonzalez** [comment]
I think both is good :)

**Comment by pelletier** [comment]
Btw, I’m just experimenting with master at the moment. When I figure out the whole process all releases will have their nanties and checksums attached

**Comment by pelletier** [comment]
@josegonzalez added the checksums to the release's notes directly too: https://github.com/pelletier/go-toml/releases/tag/latest

**Comment by josegonzalez** [comment]
Not sure I see it in that release?

**Comment by pelletier** [comment]
Err sorry, wrong link: https://github.com/pelletier/go-toml/releases/tag/v1.7.0

**Comment by josegonzalez** [comment]
👏 Amazing!

**Comment by pelletier** [comment]
Great :)
