### ISSUE TITLE
Expose more of the internals (writeToOrdered)

### ISSUE THREAD

**Issue by skyzyx** [pelletier/go-toml#349]
**Is your feature request related to a problem? Please describe.**

I would like to have more control over how the TOML is written.

**Describe the solution you'd like**

I would like it if you exposed `writeToOrdered` as a public method.

https://github.com/pelletier/go-toml/blob/3f7178ffd6cab79ef1fe4cefdd2579addf06452a/tomltree_write.go#L277

**Describe alternatives you've considered**

The `NewEncoder()` API does not provide the granular control I'm looking for.

**Comment by pelletier** [comment]
Thank you for the request! Could you elaborate on the use-case? The goal is to have `Encoder` be the "low-level" interface when generating TOML documents, so that the implementation (`writeToOrdered` for instance) is free to change.

**Comment by skyzyx** [comment]
Finally coming up for air. Sorry about the delay.
