### ISSUE TITLE
No way to retrieve keys containing dots

### ISSUE THREAD

**Issue by squirkle** [pelletier/go-toml#35]
[TOML allows for quoted keys containing dots](https://github.com/toml-lang/toml#table), but the TomlTree.Get() reads the dots as nested keys.  Is there any way to retrieve the values of keys containing dots?

**Comment by squirkle** [comment]
Apologies for posting before digging further into the source code: it is possible to achieve this by calling `myTomlTree.GetPath([]string{"key.with.dots"})`

**Comment by pelletier** [comment]
@squirkle Maybe we should find a way to query dotted keys using `Get()` (or at the very least write the workaround in the README).

We should look at other libraries, see how they handle that. What do you think about escaping the query sequence? Like `tree.Get("toplevel.key\.with\.dot")`.

**Comment by squirkle** [comment]
I'm not sure escaping dots makes the most sense here.  What about using something like: 

    tree.Get(`toplevel."key.with.dot"`)

**Comment by pelletier** [comment]
You're right, using quotes makes more sense, since it would be a step towards TOML 0.4.0 support.

**Comment by eanderton** [comment]
If it helps, the Query facility can already do this, albeit in an oblique way. 

The "Union Operator" allows quoted strings.  So a query like:
```
tree.Query(`toplevel.["key.with.dot"]`)
```
...is possible today. :)   If it's desirable, the definition of a `parseMatchExpr()` could be expanded to accept for a `tokenString` as well as a `tokenKey`, which would allow this:
```
tree.Query(`toplevel."key.with.dot"`)
```
See: https://github.com/pelletier/go-toml/blob/master/queryparser.go#L104

**Comment by pelletier** [comment]
@squirkle If you're still interested, https://github.com/pelletier/go-toml/pull/37 should allow you to write ```tree.Get(`toplevel."key.with.dot"`)```. :)
