### ISSUE TITLE
Support leading zeroes in exponent parts of floats

### ISSUE THREAD

**Issue by pelletier** [pelletier/go-toml#360]
From TOML v1.0.0-rc1 release notes:

> Leading zeroes in exponent parts of floats are permitted.

**Comment by RiyaJohn** [comment]
I modified your Readme example to take a float value, like **4e-08 or 4e-0008 or 4e-8** And all of them printed **4e-08** as output for float64 type, not really sure what is the issue

**Comment by pelletier** [comment]
That's great news! I added this issues because this requirement came out of the new TOML spec version. I wanted to make sure we 1. make sure it works (and update go-toml if not) and 2. is covered by tests.
