### ISSUE TITLE
(1, 1): parsing error: keys cannot contain  character

### ISSUE THREAD

**Issue by Frozen-Tofu** [pelletier/go-toml#362]
I load toml from a file that was saved by `go-toml`.
```
[Cache]
  access_token = "32_fwyB5zkNPTKbU4RsuhsUusUQTtiv9cPPxv_HTGkdsNSR9VHlgjvrqcukV1wYlNUhGN0APgaGqyG1zlNVEY5SYe6Br7eDopleE7iocfpoWCVQ4_S5vtwXnLcfc43eksfKFi68a9kRR3XNJ95mKNMbAEAZCB"
  expire = 1587033085

```
But I got such an error.
[badfile.zip](https://github.com/pelletier/go-toml/files/4485817/badfile.zip)
The `Cache` is defined
```
type savedToken struct {
	AccessToken string `toml:"access_token"`
	Expire int64 `toml:"expire"`
}

type cacheToml struct {
	Cache savedToken
}
```

**Comment by Frozen-Tofu** [comment]
Oh, it's not a issue of toml-go

**Comment by AllenX2018** [comment]
Cannot reproduce. You can check my testcase here. [https://play.golang.org/p/qeGwMsU6loo](https://play.golang.org/p/qeGwMsU6loo)
What's the go-toml version are you using? Maybe put your complete testcase here?
