### ISSUE TITLE
Marshalling fails for nested arrays of tables

### ISSUE THREAD

**Issue by x-hgg-x** [pelletier/go-toml#369]
**Describe the bug**
Marshalling produces an error:
```
marshalling error: unsupported value type *toml.Tree: key = "Control"
```

**To Reproduce**
```go
tree, err := toml.Load(`
combinations = [
	[{ key = "Control" }, { key = "Q" }],
	[{ key = "Escape" }],
]
`)

if err != nil {
	fmt.Println("loading error:", err)
}

_, err = tree.Marshal()
if err != nil {
	fmt.Println("marshalling error:", err)
}
```
**Expected behavior**
There is no error when loading TOML data, so marshalling should work.

**Versions**
 - go-toml: last version of master (323fe5d)
 - go: 1.14
 - operating system: Linux

**Additional context**
Unmarshalling works:

```go
type Button struct {
	Key string
}

type Action struct {
	Combinations [][]Button
}

var action Action
err = tree.Unmarshal(&action)
if err != nil {
	fmt.Println("unmarshalling error:", err)
}

fmt.Println(action)
```

Output:
```
{[[{Control} {Q}] [{Escape}]]}
```

**Comment by pelletier** [comment]
Thank you for the bug report! That's definitely wrong.

**Comment by x-hgg-x** [comment]
For information, the [BurntSushi library](https://github.com/BurntSushi/toml) also fails with this error:
```toml: TOML array element cannot contain a table```.

I think nested arrays of table might only be expressed with inline tables in TOML (see https://github.com/toml-lang/toml/issues/353#issuecomment-220268571).

**Comment by pelletier** [comment]
The latest spec calls out 

```
points = [ { x = 1, y = 2, z = 3 },
           { x = 7, y = 8, z = 9 },
           { x = 2, y = 4, z = 8 } ]
```

And that arrays can contain any other type including arrays. I don’t see why your example shouldn’t work.

**Comment by pelletier** [comment]
I wonder if your changes at https://github.com/pelletier/go-toml/commit/f1ba6388fb5981454e4f00b757bb2235bec1f327 fix this :thinking:

**Comment by x-hgg-x** [comment]
My changes don't fix this. Since nested arrays of tables can only be represented as inline tables, we should add an inline tree representation in the [tomlValueStringRepresentation](https://github.com/pelletier/go-toml/blob/master/tomltree_write.go#L106) method. I will try to make a PR for this.
