### ISSUE TITLE
marshal: support encoding.TextMarshaler

### ISSUE THREAD

**Issue by Oncilla** [pelletier/go-toml#373]
Most go libraries that handle marshaling/unmarshaling support `encoding.TextMarshaler` when marshaling.

Similar to how types that implement the `toml.Marshaler` interface, I would like types that implement
the `encoding.TextMarshaler` to be supported.
If a type implements both `encoding.TextMarshaler` and `toml.Marshaler`. The `MarshalToml` method should take precedence.

If that is a feature you want to integrate, I would be happy to implement it.

**Comment by pelletier** [comment]
I think it’s a great idea! Thanks for calling it out. :)
