### ISSUE TITLE
[Regression] Default values for integers are not preserved while using decoder

### ISSUE THREAD

**Issue by cardil** [pelletier/go-toml#406]
**Describe the bug**
After upgrade to 1.7.0 from 1.6.0 I see a regression in default values handling. At least for integers.

**To Reproduce**

See example at https://play.golang.org/p/OAyDXl1T16K

**Expected behavior**
Using 1.6.0 version https://play.golang.org/p/OAyDXl1T16K is passing without errors

**Versions**
 - go-toml: v1.7.0 (`h1:7utD74fnzVc/cpcyy8sjrlFr5vYpypUixARcHIMIGuI=`
 - go: 1.13
 - operating system: Linux

**Comment by pelletier** [comment]
Thanks for the report! Definitely a regression, though it's part of a broader issue: https://github.com/pelletier/go-toml/issues/252.

**Comment by AllenX2018** [comment]
I think this has been fixed via 1479e10

**Comment by cardil** [comment]
Please close this issue if the fix is released in some version that I can consume

**Comment by pelletier** [comment]
Release 1.8.0 which should contain the fix for that issue: https://github.com/pelletier/go-toml/releases/tag/v1.8.0

**Comment by cardil** [comment]
Confirmed. Closing.
