### ISSUE TITLE
the returned value of MarshalTOML is not used as TOML in marshalling 

### ISSUE THREAD

**Issue by cofyc** [pelletier/go-toml#414]
**Describe the bug**

the returned value of `MarshalTOML` is used as a TOML value, not a raw TOML formatted value

**To Reproduce**

This example shows the difference between JSON/TOML marshaling:

```
package main

import (
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/pelletier/go-toml"
)

type IntOrString string

func (x *IntOrString) MarshalTOML() ([]byte, error) {
	s := *(*string)(x)
	_, err := strconv.Atoi(s)
	if err != nil {
		return []byte(fmt.Sprintf(`"%s"`, s)), nil
	}
	return []byte(s), nil
}

func (x *IntOrString) MarshalJSON() ([]byte, error) {
	return x.MarshalTOML()
}

type foo struct {
	X *IntOrString
}

func main() {
	xx := IntOrString("111")
	d := foo{
		X: &xx,
	}
	s1, _ := toml.Marshal(d)
	fmt.Printf("toml:\n%s\n", string(s1))
	s2, _ := json.Marshal(d)
	fmt.Printf("json:\n%s\n", string(s2))
}
```

The current output is:

```
toml:
X = "111"

json:
{"X":111}
```

See https://play.golang.org/p/8RbpHT0v86L

**Expected behavior**

The returned value of MarshalYAML should be used as a valid TOML, otherwise, it can't be used to generate TOML for customized types.

The expected output of the above program:

```
toml:
X = 111

json:
{"X":111}
```

**Versions**
 - go-toml: 1.8.0
 - go: 1.13.9
 - operating system: os neutral 

**Additional context**
Add any other context about the problem here that you think may help to diagnose.

**Comment by cofyc** [comment]
cc @pelletier what do you think?

**Comment by pelletier** [comment]
Thanks for reporting this! This behavior is not correct, we should mimic `encoding/json`'s.

**Comment by pelletier** [comment]
This should have been fixed in https://github.com/pelletier/go-toml/commit/05bf3807d36905c612e6008563dbe372a0c85f4c.

Let me know if that's not the case!
