### ISSUE TITLE
Remove/Separate benchmarking dependencies

### ISSUE THREAD

**Issue by diamondburned** [pelletier/go-toml#418]
I think this module, as a TOML parser, shouldn't depend on another TOML and YML parser for benchmarking.

It would probably be best if another repository could be made for benchmarks that rely on other libraries such as BurntSushi's. Otherwise, I think it's better to remove the benchmarks.

For reference, here's the [`go.mod` as of this issue][1]: 

```
module github.com/pelletier/go-toml

go 1.12

require (
	github.com/BurntSushi/toml v0.3.1 // for benchmarking
	github.com/davecgh/go-spew v1.1.1
	gopkg.in/yaml.v2 v2.3.0 // also for benchmarking
)
```

[1]: https://github.com/pelletier/go-toml/blob/44aed552fd90fee7c7be07fd89f75b98e9fcadef/go.mod#L6

**Comment by pelletier** [comment]
I agree, would be better with no dependency. I'd still like to keep the benchmarks around in this repository. Wonder if we can put them in a sub-folder with their dedicated `go.mod` file.

**Comment by AllenX2018** [comment]
Good idea. I will try to move them to a sub-folder like "benchmark" with a dedicated `go.mod` file
