### ISSUE TITLE
Is there a simple way of unmarshalling directly from a toml file?

### ISSUE THREAD

**Issue by cezane** [pelletier/go-toml#422]
I would like to know how to unmarshal a toml file. I saw that the unmarshal function receives a byte array. But I want to unmashal the data from a file. And I do not want to work with the Tree option.

I do not know if this place is the best to answer. If it is not, please indicate me where I can get this information.

Thank you.

**Comment by KenjiTakahashi** [comment]
This should work:
```go
fi, err := os.Open("file.toml")
err = toml.NewDecoder(fi).Decode(&outStruct)
```
Not as "simple" as BurntSushi's `toml.DecodeFile`, but it is what it is :-).

**Comment by AllenX2018** [comment]
@KenjiTakahashi is right. That's how to unmarshal a toml file. Feel free to reopen this issue if you have any other question.
