### ISSUE TITLE
Multiline string generates invalid TOML on valid Go strings

### ISSUE THREAD

**Issue by danneu** [pelletier/go-toml#424]
**Describe the bug**

Since the lib does less escaping when generating multiline strings, it doesn't generate an equivalent string between multiline and singleline mode.

I would expect (1) that flipping multiline=true can't break my toml and (2) that any valid Go string should produce a valid toml string. As it currently stands, you have to know in advance that your strings are "safe" to use with multiline which seems like a bug. I would expect multiline mode to merely use `"""` instead of `"`, and to avoid escaping newlines.

**To Reproduce**

Demo: https://repl.it/@danneu/RegalFreeLicense#main.go

```go
package main

import (
  "fmt"
  "github.com/pelletier/go-toml"
)

type Message1 struct {
  Text string
}

type Message2 struct {
  Text string `multiline:"true"`
}

func main() {
  msg1 := Message1{"Hello\\World"}
  msg2 := Message2{"Hello\\World"}
  toml1, err := toml.Marshal(msg1)
  if err != nil {
    panic(err)
  }
  toml2, err := toml.Marshal(msg2)
  if err != nil {
    panic(err)
  }

  fmt.Printf("toml1: %s\n", toml1)
  fmt.Printf("toml2: %s\n", toml2)

  // Message1 round-trips successfully 
  msg1parsed := Message1{}
  err = toml.Unmarshal(toml1, &msg1parsed)
  if err != nil {
    panic(err)
  }
  fmt.Printf("round tripped msg1: %#v\n", msg1parsed)
  // => round tripped msg1: main.Message1{Text:"Hello\\World"}

  // Message2 does not round-trip due to missing escape 
  msg2parsed := Message2{}
  err = toml.Unmarshal(toml2, &msg2parsed)
  if err != nil {
    panic(err)
  }
  fmt.Printf("round tripped msg2: %#v\n", msg2parsed)
  // => panic: (2, 1): invalid escape sequence: \W
}
```

**Expected behavior**

I would expect the same input to produce byte-equiv output and for Message2 to not break on valid Go strings.

**Versions**
 - go-toml: v1.8.0
 - go: 1.14
 - operating system: macOS

**Additional context**

This is because generateMultilineTomlString() does less escaping than generateTomlString() when I think they should do the same escaping with the one exception being \r and \n.

Maybe the current code was written at a time when you were using `'''` instead of `"""`?

**Comment by AllenX2018** [comment]
Thanks for reporting.

**Comment by danneu** [comment]
I vendored and patched this for my own needs.

The change to `encodeMultilineTomlString` was simply:

```diff
- case '\\':
-     b.WriteString(`\`)
+ case '\\':
+     b.WriteString(`\\`)
```

**Comment by pelletier** [comment]
This has been fixed in the upcoming go-toml v2! https://github.com/pelletier/go-toml/commit/21445f51702aabd46132374c38c08eb832063e68

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
