### ISSUE TITLE
Go 1.15rc1 error format change in ParseDuration

### ISSUE THREAD

**Issue by eclipseo** [pelletier/go-toml#428]
**Describe the bug**
```
Testing    in: /builddir/build/BUILD/go-toml-1.8.0/_build/src
         PATH: /builddir/build/BUILD/go-toml-1.8.0/_build/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
       GOPATH: /builddir/build/BUILD/go-toml-1.8.0/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test -buildmode pie -compiler gc -ldflags "-X github.com/pelletier/go-toml/version=1.8.0 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '"
      testing: github.com/pelletier/go-toml
github.com/pelletier/go-toml
{Hello 3.5 {One} [{Two} {Three}]}
--- FAIL: TestUnmarshalBadDuration (0.00s)
    marshal_test.go:2157: unexpected error: (1, 1): Can't convert 1z(string) to time.Duration. time: unknown unit "z" in duration "1z"
FAIL
```

**To Reproduce**
Running go test.

**Expected behavior**
Tests pass.

**Versions**
 - go-toml: version 1.8.0
 - go: version Go 1.15 rc 1
 - operating system: Fedora Linux Rawhide

**Additional context**
The error message was modified to add quote around 1z and z, so it is not recognized by
https://github.com/pelletier/go-toml/blob/34de94e6a887dcd421ab7586d76d26ee5ab3d96a/marshal_test.go#L2199

**Comment by moorereason** [comment]
Due to https://github.com/golang/go/commit/201cb046b745f8bb00e3d382290190c74ba7b7e1.

**Comment by pelletier** [comment]
Good catch! Thank you for reporting.

**Comment by pelletier** [comment]
This should be fixed in the latest commit. Feel free to reopen if it doesn't work for you. Sorry it took so long :(
