### ISSUE TITLE
TOMLUnmarshaler without the actual TOML object in file causes a nil ptr dereference

### ISSUE THREAD

**Issue by diamondburned** [pelletier/go-toml#431]
**Describe the bug**
Unmarshaling into a struct containing a field that implements `UnmarshalTOML` will cause a nil pointer dereference panic if the TOML object is not there in the tree.

**To Reproduce**

<details>
<summary>Go code to reproduce (or <a href="https://play.golang.org/p/pFhlhqksYgE">playground</a>)</summary>

```go
type Config struct {
	Key string `toml:"key"`
	Obj Custom `toml:"obj"`
}

type Custom struct {
	v string
}

func (c *Custom) UnmarshalTOML(v interface{}) error {
	return nil
}

const t = `key = "value"`

func main() {
	t, err := toml.LoadBytes([]byte(t))
	if err != nil {
		panic(err)
	}

	var c Config

	if err := t.Unmarshal(&c); err != nil {
		panic(err)
	}

	fmt.Printf("%#v\n", c)
}
```

</details>

<details>
<summary>Panic stack trace</summary>

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x503368]

goroutine 1 [running]:
github.com/pelletier/go-toml.(*Tree).ToMap(0x0, 0x56f600)
	/home/diamond/.go/pkg/mod/github.com/pelletier/go-toml@v1.8.0/tomltree_write.go:502 +0x48
github.com/pelletier/go-toml.(*Decoder).valueFromTree(0xc000163f10, 0x56f600, 0x523720, 0x0, 0xc00012c2c0, 0xc00012c210, 0x199, 0xa, 0x10, 0xc0001360c8)
	/home/diamond/.go/pkg/mod/github.com/pelletier/go-toml@v1.8.0/marshal.go:720 +0x112
github.com/pelletier/go-toml.(*Decoder).valueFromTree(0xc000163f10, 0x56f600, 0x526660, 0xc0001183c0, 0xc000163e18, 0x199, 0xc00013c240, 0x0, 0xc000163e30, 0x40bae6)
	/home/diamond/.go/pkg/mod/github.com/pelletier/go-toml@v1.8.0/marshal.go:826 +0x887
github.com/pelletier/go-toml.(*Decoder).unmarshal(0xc000163f10, 0x511b60, 0xc00012c200, 0xc0001183c0, 0x0)
	/home/diamond/.go/pkg/mod/github.com/pelletier/go-toml@v1.8.0/marshal.go:698 +0x275
github.com/pelletier/go-toml.(*Tree).Unmarshal(...)
	/home/diamond/.go/pkg/mod/github.com/pelletier/go-toml@v1.8.0/marshal.go:585
main.main()
	/tmp/tomltest/main.go:39 +0x143
exit status 2
```

</details>

**Expected behavior**
Unmarshaler should not crash and instead should just not call `UnmarshalTOML` and leave the value as it is.

**Versions**
 - go-toml: version 1.8.0
 - go: version 1.14.6
 - operating system: linux/amd64 on NixOS

**Additional context**
A workaround to this bug would be to check if the TOML object exists, and insert an empty one if it does not. The code below fixes it when placed right before `Unmarshal`:

```go
if !t.Has("obj") {
	t.Set("obj", Custom{})
}
```

**Comment by AllenX2018** [comment]
Thanks for reporting! I will check it.

**Comment by x1unix** [comment]
I confirm this issue - https://goplay.tools/snippet/xIrajrYGAgv

Also notified that although I implemented `TOMLUnmarshaler` interface, this method is not used and I get this error:

```
Can't convert 32m(string) to main.DurationString
```

(reproducible in playground, just uncomment test config field)

**Comment by x1unix** [comment]
@AllenX2018 the fix is to add nil-check in `marshal.go:720`

```diff
	// Check if pointer to value implements the Unmarshaler interface.
	if mvalPtr := reflect.New(mtype); isCustomUnmarshaler(mvalPtr.Type()) {
		d.visitor.visitAll()

+		mVal := tval.ToMap()
+		if mVal == nil {
+			return mvalPtr.Elem(), nil
+		}
+		
+		if err := callCustomUnmarshaler(mvalPtr, mVal); err != nil { 
-		if err := callCustomUnmarshaler(mvalPtr, tval.ToMap()); err != nil {
			return reflect.ValueOf(nil), fmt.Errorf("unmarshal toml: %v", err)
		}
		return mvalPtr.Elem(), nil
	}
```

**Comment by x1unix** [comment]
@diamondburned you can implement `TextUnmarshaler` as workaround, see https://github.com/pelletier/go-toml/issues/437

**Comment by pelletier** [comment]
Hi! This issue should be fixed in master. Feel free to reopen if it does not work for you!

**Comment by x1unix** [comment]
@pelletier when do you plan to make a new major release that includes this fix?

**Comment by pelletier** [comment]
Just tagged 1.8.1 which contains that fix
