### ISSUE TITLE
Support Unmarshal into empty interface{}

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#432]
**Is your feature request related to a problem? Please describe.**
While looking at migrating [Hugo](https://github.com/gohugoio/hugo) from BurntSushi to this package, I found that this package doesn't support unmarshaling into an empty `interface{}`.  Returns an error "_only a pointer to struct or map can be unmarshaled from TOML._"

**Describe the solution you'd like**
When an empty `interface{}` is passed to `toml.Unmarshal` as the `v` parameter, decode as a `map[string]interface{}`.

**Describe alternatives you've considered**
Stick with BurntSushi. 😞 

**Additional context**
* Desired usage:  https://play.golang.org/p/CKHM44HsRgP
* JSON stdlib does this: https://play.golang.org/p/oM0Y08WGuf5
* yaml.v3 does this: https://play.golang.org/p/IMAelUFHQ_p (yaml.v2 creates a `map[interface{}]interface{}`, but that idea was abandoned in v3)

**Comment by pelletier** [comment]
Totally right, go-toml should be able to do that. At that point I don't see any blocker to support it -- except finding the time to actually do the work.
