### ISSUE TITLE
Does not support structure nesting? 

### ISSUE THREAD

**Issue by olongfen** [pelletier/go-toml#435]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. Including TOML files.

**Expected behavior**
A clear and concise description of what you expected to happen, if other than "should work".

**Versions**
 - go-toml: version (git sha)
 - go: version
 - operating system: e.g. macOS, Windows, Linux

**Additional context**
Add any other context about the problem here that you think may help to diagnose.

**Comment by pelletier** [comment]
Hi, as your question is rather vague, could you fill out the issue template so that we can help? Thank you!

**Comment by olongfen** [comment]
```go

package main

import (
	"fmt"
	"github.com/pelletier/go-toml"
)

type TemplateOne struct {
	FiledOne string
	FiledTwo string
	Data     map[string]interface{}
}

type TemplateTwo struct {
	FiledOne string
	FiledTwo string
}

func main() {
	t := TemplateOne{}
	t.Data = map[string]interface{}{}
	t.Data["demo"] = TemplateTwo{}
	fmt.Println(toml.TreeFromMap(t.Data))

}
```


output:  cannot convert type main.TemplateTwo to Tree

**Comment by AllenX2018** [comment]
> ```go
> func (e *Encoder) marshal(v interface{}) ([]byte, error) {
> 	mtype := reflect.TypeOf(v)
> 	if mtype.Kind() != reflect.Struct {
> 		return []byte{}, errors.New("Only a struct can be marshaled to TOML")
> 	}
> 	sval := reflect.ValueOf(v)
> 	if isCustomMarshaler(mtype) {
> 		return callCustomMarshaler(sval)
> 	}
> 	t, err := e.valueToTree(mtype, sval)
> 	if err != nil {
> 		return []byte{}, err
> 	}
> 
> 	var buf bytes.Buffer
> 	_, err = t.writeTo(&buf, "", "", 0, e.arraysOneElementPerLine)
> 
> 	return buf.Bytes(), err
> }
> 
> // i don't konw why can't be mashal map in this way ? 
> ```

Hi. I've try your testcase and `toml.Marshal` can encode the `Data` field correctly the the error it return is nil. I guess you're using the old version. Can you try the latest version of go-toml?

**Comment by olongfen** [comment]
thank you
