### ISSUE TITLE
Allow Encode to non-inline array of tables

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#436]
**Is your feature request related to a problem? Please describe.**
Not really.  Comparing differences with BurntSushi while testing in Hugo.

**Describe the solution you'd like**
I would like the ability to Encode non-inline arrays of tables.

**Describe alternatives you've considered**
Currently using BurntSushi.

**Additional context**
Example program (requires https://github.com/pelletier/go-toml/commit/b76eb6211757490046121712dc5c7b10d5f8fec9):

```go
package main

import (
        "bytes"
        "encoding/json"
        "fmt"

        "github.com/pelletier/go-toml"
)

func main() {
        data := []byte(`{"a": [ { "b": { "c": "d" } } ]}`)

        var v interface{}
        err := json.Unmarshal(data, &v)
        if err != nil {
                panic(err)
        }

        var buf bytes.Buffer
        err = toml.NewEncoder(&buf).Encode(v)
        if err != nil {
                panic(err)
        }

        fmt.Printf("%s", buf.String())
}
```
Output:
```
a = [{ b = { c = "d" } }]
```
Desired Output:
```
[[a]]

  [a.b]
  c = "d"
```

**Comment by pelletier** [comment]
Good idea. Sounds like a new `Encoder` option.

**Comment by 89z** [comment]
Hey your desired output is confusing, you can use this instead:

~~~
[[a]]
b = { c = "d" }
~~~

**Comment by 89z** [comment]
https://github.com/gohugoio/hugo/issues/7799

**Comment by moorereason** [comment]
@89z,
The desired output purposely doesn't use inline tables.

**Comment by 89z** [comment]
Ah, I see. I think it would be nice if we could tag the tables somehow. I have documents where I want some inline, and some not inline.

**Comment by pelletier** [comment]
@moorereason @89z as you know I'm working on v2; I am now considering the implementation of `Marshal()`.

Do you have thoughts on the API of this feature? How would you like to be able to specify which tables should be inline and some not?

**Comment by 89z** [comment]
At the time I was trying to use TOML as a sort of flat file database. I realized pretty quickly that it wasnt a good fit, as I didnt really find an implementation (in any language) that had good control over Marshalling. In the end I just went with SQLite.

Not sure if that answers your question.

**Comment by pelletier** [comment]
That's good feedback! If it turns out there is no real use-case for that kind of fine-grained control of marshaling there is no point in adding complexity to the codebase for it.

**Comment by pelletier** [comment]
Cool. I think it is reasonable to limit the tuning to either the whole 
document or specific struct fields (as opposed to arbitrary paths into 
maps/slices). I'll get started on Marshal() and let you know when I have 
something working.

**Comment by pelletier** [comment]
V2 marshaler does this by default now https://github.com/pelletier/go-toml/commit/606ddf13150ce5ff7650786abaf12de29b73d7e8!

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
