### ISSUE TITLE
Unmarshaler doesn't respect Unmarshaler interface on type mismatch 

### ISSUE THREAD

**Issue by x1unix** [pelletier/go-toml#437]
**Describe the bug**

Decoder doesn't respect Unmarshaler interface if source (toml) and destination value types are different.
For example if source type is `string` but unmarshaled onto struct which implements `Unmarshaler` interface.

I found a workaround by implementing `TextUnmarshaler` interface, but if it's an expected behavior - it should be documented.

**To Reproduce**

See demo - https://goplay.tools/snippet/Dxp0lfxX7Dy

**Expected behavior**

Instead of complaining about types, decoder should just pass value to `Unmarshaler` like `encoding/json` package does.

**Versions**
 - go-toml: [v1.8.0](https://github.com/pelletier/go-toml/releases/tag/v1.8.0)
 - go: 1.15
 - operating system: Linux

**Additional context**

N/A

**Comment by pelletier** [comment]
Definitely looks wrong. Thank you for reporting!

**Comment by pelletier** [comment]
Actually, I think you're correct in this sentence:

> I found a workaround by implementing TextUnmarshaler interface, but if it's an expected behavior - it should be documented.

Looking at the code, this is the expectation. `encoding.TextUnmarshaler` is defined as

> TextUnmarshaler is the interface implemented by an object that can unmarshal a textual representation of itself.

which is the expected action here.

`toml.Unmarshaler` is poorly defined as

> Unmarshaler is the interface implemented by types that can unmarshal a TOML description of themselves.

In the code today `toml.Unmarshaler` is used to unmarshal structures (its argument are maps and slices), while `encoding.TextUnmarshaler` is used to unmarshal leaves of the tree (strings).

It's insanely confusing.

Things we could do:

1. Improve the documentation to state the expectation around `toml.Unmarshaler`.
2. Call `toml.Unmarshaler` on leaves, passing a string as an argument.

Seems like we should do 1. no matter what. More docs never hurt.

I'm hesitant to go with two, given we will probably want to change that interface in a later version to match more closely what `encoding/json` does:

>To unmarshal JSON into a value implementing the Unmarshaler interface, Unmarshal calls that value's UnmarshalJSON method, including when the input is a JSON null. Otherwise, if the value implements encoding.TextUnmarshaler and the input is a JSON quoted string, Unmarshal calls that value's UnmarshalText method with the unquoted form of the string.

Thoughts?

**Comment by x1unix** [comment]
@pelletier imho it's confusing to have two different unmarshal interfaces (toml and text), especially considering that custom unmarshal types mostly used for exotic values like UUID's (most implementations store it as fixed-length array), dates, etc.

Is it possible to just pass Go value to `toml.Unmarshaler` and omit type check (`toml.Unmarshaler is struct`) and leave type checking to interface implementation (which should be present anyway for safe interface casting without panic)?

**Comment by pelletier** [comment]
Sounds good. https://github.com/pelletier/go-toml/pull/444 How does that work for you?

**Comment by x1unix** [comment]
@pelletier looks great! thank you!
