### ISSUE TITLE
Try fuzzy testing

### ISSUE THREAD

**Issue by pelletier** [pelletier/go-toml#44]
https://github.com/dvyukov/go-fuzz

Could be interesting to give it a try. This is related to #42.

**Comment by landaire** [comment]
I started fuzzing today and have found ~42 crashes/hangs so far. I'll be posting in about an hour when I get home so apologize if you get spammed with emails!

**Comment by pelletier** [comment]
Thank you very much for doing this! I'm interested in what is going to come out. Especially concerning the hangs.
If you decide to create individual issues, do you mind using the [fuzz](https://github.com/pelletier/go-toml/labels/fuzzy) label please?

**Comment by landaire** [comment]
Will do!

**Comment by landaire** [comment]
@pelletier I think that as a non-collaborator I'm unable to assign labels to my own issues. I tried with [this issue](https://github.com/pelletier/go-toml/issues/48) but the options are disabled.

**Comment by pelletier** [comment]
Ah indeed. [It seems like](https://help.github.com/articles/creating-an-issue/) you can't assign a label if you not a maintainer. Don't worry about the labels, I will take care of them.

Thank you for https://github.com/pelletier/go-toml/issues/48! Turns out it was a bug I already knew about and fixed in the meantime. :)

**Comment by pelletier** [comment]
Closing this as we did it and fixed some bugs along the way. Anybody is welcome to try again and reopen an issue if a bug is found! :)
