### ISSUE TITLE
SetPath() doesn't set the values of all the paths if toml contains array of tables.

### ISSUE THREAD

**Issue by heyaWorld** [pelletier/go-toml#445]
**Describe the bug**
(*Tree).SetPath() doesn't set the values of all the paths if toml contains array of tables.

**To Reproduce**

```
    config := `
	[[inputs.nginx]]
		urls = ["http://127.0.0.1:9090/nginx_status"]
		response_timeout = '5s'
		[inputs.nginx.tags]
		newmetric1 = "insights1"
	
	[[inputs.nginx]]
		urls = ["http://127.0.0.1:9090/nginx_status"]
		response_timeout = '5s'
	
	[inputs.nginx.tags]
		foo1 = "bar1"
	
	[[inputs.cpu]]`

	// Load config, output is *Tree
	tree, _ := toml.Load(config)
	node := tree.GetPath([]string{"inputs"}).(*toml.Tree)
	for _, key := range node.Keys() {
		tree.SetPath([]string{"inputs", key, "tags", "computer"}, "mycomputerName")
		tree.SetPath([]string{"inputs", key, "tags", "origin"}, "telegraf/apache")
	}
	fmt.Println(tree)
```
   
**Expected behavior**
SetPath should add values for all the matching keys.

Toml tree after running the above code:

```
[inputs]

  [[inputs.cpu]]

    [inputs.cpu.tags]
      computer = "mycomputerName"
      origin = "telegraf/apache"

  [[inputs.nginx]]
    response_timeout = "5s"
    urls = ["http://127.0.0.1:9090/nginx_status"]

    [inputs.nginx.tags]
      newmetric1 = "insights1"

  [[inputs.nginx]]
    response_timeout = "5s"
    urls = ["http://127.0.0.1:9090/nginx_status"]

    [inputs.nginx.tags]
      computer = "mycomputerName"
      foo1 = "bar1"
      origin = "telegraf/apache"

```

Expected toml tree:

```
`[inputs]

  [[inputs.cpu]]

    [inputs.cpu.tags]
      computer = "mycomputerName"
      origin = "telegraf/apache"

  [[inputs.nginx]]
    response_timeout = "5s"
    urls = ["http://127.0.0.1:9090/nginx_status"]

    [inputs.nginx.tags]
      computer = "mycomputerName"
      origin = "telegraf/apache"
      newmetric1 = "insights1"

  [[inputs.nginx]]
    response_timeout = "5s"
    urls = ["http://127.0.0.1:9090/nginx_status"]

    [inputs.nginx.tags]
      computer = "mycomputerName"
      foo1 = "bar1"
      origin = "telegraf/apache"`
```

**Versions**
 - go-toml: version (v1.8.1)
 - go: version go1.14 windows/amd64
 - operating system: windows

**Additional context**
SetPath should be able to set values for all the matching paths instead of the first matching path or (*Tree).Keys() should return multiple same keys with some kind of identifier.

**Comment by pelletier** [comment]
Thank you for reporting this!

The code [explicitly picks](https://github.com/pelletier/go-toml/blob/master/toml.go#L339-L345) the last element of the array. Your expectation of having it update all the matching arrays seems fair. I don't see any use case where one would expect `SetPath` to just update the last one.

**Comment by heyaWorld** [comment]
Yep that makes sense. Thank you!

**Comment by RiyaJohn** [comment]
@pelletier I would like to work on this issue, I made some changes that could give the expected output. But I would like to check with you if this is what you were look for, before I look into those failing test cases.

**Comment by pelletier** [comment]
@RiyaJohn Awesome!

I looked at https://github.com/RiyaJohn/go-toml/commit/3fe4f1b160a41d7be43229d73711cd6d49eb3d91. I think you are going in the right direction!

**Comment by heyaWorld** [comment]
@RiyaJohn thanks for picking up this issue. But are you planning to merge your changes? If not, I can also pick up your changes and can test them out and see if everything works fine or not. Thanks!

**Comment by RiyaJohn** [comment]
> @RiyaJohn thanks for picking up this issue. But are you planning to merge your changes? If not, I can also pick up your changes and can test them out and see if everything works fine or not. Thanks!

Hey @heyaWorld You can pick up my changes and go ahead. I did try fixing the test cases, that involved having to change some code to satisfy two different use-cases. But really couldn't put enough time on this task. So, yes please go ahead

**Comment by prakashmirji** [comment]
have same requirement. looking for this fix to be merged. any plans when this is getting merged? or any alternative solutions?

**Comment by pelletier** [comment]
Happy to take a pull request if that is still being worked on!

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released, and it seems like this issue is not in scope for v2. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1). If you believe this is a mistake please reach out!
