### ISSUE TITLE
Is there a good way to modify a toml file?

### ISSUE THREAD

**Issue by mq0427** [pelletier/go-toml#457]
Is there a good way to modify a toml file? I just have to modify the value of some keys. And I would like to just keep all the other things unchanged, such as the order of the keys and the comments. It seems it can be achieved by LoadFile and then set the new value and call WriteTo to overwrite the toml file, but the original layout like  the order of the keys and the comments will be lost.

**Comment by pelletier** [comment]
Unfortunately not yet. As far as I know the best you can do today is to decide that the file should always be "linted" and have go-toml sort it on write.

Edit-in-place is definitely something I would love to see as well. Most of the pieces are already there: `LoadFile` keeps track of positions of what it read, and `Encoder` has some logic to change what order things should be emitted.

**Comment by mq0427** [comment]
@pelletier, thanks for reply. Any plans to support "Edit-in-place"?

**Comment by pelletier** [comment]
Not personally -- my free time has been close to non-existent lately, as the delay in this reply shows. If anyone wants to tackle this I'll happily review pull requests.

**Comment by prakashmirji** [comment]
I am also looking for this feature. We want to edit some keys or add new keys through programmatically.

**Comment by pelletier** [comment]
Thanks for your interest in go-toml! I'm currently working (albeit slowly) on defining the document editing interface for go-toml v2. It should address this issue.

If you have ideas or examples of what you'd like it to look like I'd love to see them!

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released, and document manipulation is out of scope for v2. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1). If you believe this is a mistake please reach out!
