### ISSUE TITLE
Slice should be []interface{}

### ISSUE THREAD

**Issue by 89z** [pelletier/go-toml#458]
With JSON, [json#Unmarshal][1] defines this output:

~~~
[]interface{}, for JSON arrays
map[string]interface{}, for JSON objects
~~~

So you can have a program like this and it works as expected:

~~~go
package main

import (
   "encoding/json"
   "fmt"
   "log"
   "strings"
)

type Map map[string]interface{}
type Slice []interface{}

func (m Map) A(s string) Slice {
   return m[s].([]interface{})
}

func main() {
   s := `{"package": [{
      "dependencies": ["regex"],
      "name": "decode",
      "version": "0.1.0"
   }]}`
   o := strings.NewReader(s)
   m := Map{}
   e := json.NewDecoder(o).Decode(&m)
   if e != nil {
      log.Fatal(e)
   }
   a := m.A("package")
   fmt.Println(a)
}
~~~

However if you create the same program with TOML:

~~~go
package main

import (
   "fmt"
   "github.com/pelletier/go-toml"
   "log"
   "strings"
)

type Map map[string]interface{}
type Slice []interface{}

func (m Map) A(s string) Slice {
   return m[s].([]interface{})
}

func main() {
   s := `[[package]]
dependencies = ["regex"]
name = "decode"
version = "0.1.0"`
   o := strings.NewReader(s)
   m := Map{}
   e := toml.NewDecoder(o).Decode(&m)
   if e != nil {
      log.Fatal(e)
   }
   a := m.A("package")
   fmt.Println(a)
}
~~~

It completely fails:

~~~
panic: interface conversion: interface {} is []map[string]interface {}, not
[]interface {}
~~~

For some reason the TOML package thinks Slice is `[]map[string]interface{}`,
instead of the proper `[]interface{}` like JSON. Same problem exists for
`toml#Unmarshal` and `toml#Tree.Unmarshal`. Only way I could get expected result
is using the below program. Why was TOML designed counter to the JSON package,
and can this be fixed?

~~~go
package main

import (
   "fmt"
   "github.com/pelletier/go-toml"
   "log"
)

type Map map[string]interface{}
type Slice []interface{}

func (m Map) A(s string) Slice {
   return m[s].([]interface{})
}

func main() {
   s := `[[package]]
dependencies = ["regex"]
name = "decode"
version = "0.1.0"`
   o, e := toml.Load(s)
   if e != nil {
      log.Fatal(e)
   }
   m := Map(o.ToMap())
   a := m.A("package")
   fmt.Println(a)
}
~~~

[1]://golang.org/pkg/encoding/json#Unmarshal

**Comment by 89z** [comment]
https://github.com/gohugoio/hugo/issues/7799

**Comment by 89z** [comment]
As a workaround, this seems to perform as expected:

https://github.com/naoina/toml

**Comment by 89z** [comment]
As a workaround, I wrote a function that wraps `ToMap`:

~~~go
func TomlDecode(s string) (Map, error) {
   o, e := toml.Load(s)
   if e != nil {
      return nil, e
   }
   return o.ToMap(), nil
}
~~~

found here:

https://github.com/knadh/koanf/blob/e0853799/parsers/toml/toml.go#L19-L25

**Comment by pelletier** [comment]
Thank you for reporting this! It's probably a bug in the unmarshalling code. It was poorly designed at the time; I don't see any reason why this couldn't work.

**Comment by 89z** [comment]
I was afraid you would say something like "it cant change now because of backward compatability". I think it should be changed if possible to match the JSON package. I am not great at Go, but I can try to work up a PR if need be.

**Comment by pelletier** [comment]
Hi! As I'm wrapping up the unmarshaler of go-toml v2, I've noticed that this bug has been resolved over there => https://github.com/pelletier/go-toml/commit/c3fc668f27bfaf613524c3496d830765a4845223

Any chance you can use this version? Only the unmarshaler is implemented, but it passes a superset of the v1 tests.

**Comment by 89z** [comment]
sorry but I dont know how to make it work off a branch. Dont know why Go has to make it so hard.

**Comment by pelletier** [comment]
If you're using go modules, you should be able to `go get github.com/pelletier/go-toml/v2@c3fc668f27bfaf613524c3496d830765a4845223`, and update your go-toml import path to `github.com/pelletier/go-toml/v2`.

**Comment by 89z** [comment]
can you give me an example program or something? the code in the original post doesnt work with the new API

**Comment by pelletier** [comment]
Added the Decoder interface in a new commit. This should do it:

```
cat > main.go <<'EOF'
package main

import (
   "fmt"
   "github.com/pelletier/go-toml/v2"
   "log"
   "strings"
)

type Map map[string]interface{}
type Slice []interface{}

func (m Map) A(s string) Slice {
   return m[s].([]interface{})
}

func main() {
   s := `[[package]]
dependencies = ["regex"]
name = "decode"
version = "0.1.0"`
   o := strings.NewReader(s)
   m := Map{}
   e := toml.NewDecoder(o).Decode(&m)
   if e != nil {
      log.Fatal(e)
   }
   a := m.A("package")
   fmt.Println(a)
}
EOF

go mod init example.com/m
go get github.com/pelletier/go-toml/v2@2714786b3791d1eed1361c877ab8fea6b4421af7
go run main.go
```

prints

```
[map[dependencies:[regex] name:decode version:0.1.0]]
```

**Comment by 89z** [comment]
Thats weird, your two `go get` commands are different...

**Comment by pelletier** [comment]
> Added the Decoder interface in a new commit. 

The second `go get` comment references the new commit, so that the existing program in the issue works.

**Comment by 89z** [comment]
ok yes, the program in the original post works now, if I use `/v2`
