### ISSUE TITLE
Whitespace around dot-separated parts should be ignored

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#475]
According to the TOML spec ([since v0.5.0](https://github.com/toml-lang/toml/commit/aa10486317fdc4efc71ba0100a2c79c70464f3a4) it appears), whitespace around dot-separated parts should be ignored (I'm assuming this means unquoted keys, but I digress).  A clear example was [added to the v1.0.0 spec](https://github.com/toml-lang/toml/commit/b7f24c07cd42de1db613ebabc2773e9e924cf958):

```
fruit.name = "banana"     # this is best practice
fruit. color = "yellow"   # same as fruit.color
fruit . flavor = "banana" # same as fruit.flavor
```

The following change to an existing parser test appears to fail:

```diff
diff --git a/parser_test.go b/parser_test.go
index 60fa375..1a7494b 100644
--- a/parser_test.go
+++ b/parser_test.go
@@ -1104,7 +1104,7 @@ func TestDottedKeys(t *testing.T) {
        tree, err := Load(`
 name = "Orange"
 physical.color = "orange"
-physical.shape = "round"
+physical. shape = "round"
 site."google.com" = true`)

        assertTree(t, tree, err, map[string]interface{}{
```

```
$ go test -run=TestDottedKeys
--- FAIL: TestDottedKeys (0.00s)
    parser_test.go:42: Asserting tree:
         (*toml.Tree)(<nil>)

    parser_test.go:15: Non-nil error: (4, 11): was expecting token =, but got "shape" instead
    parser_test.go:44: Finished tree assertion.
FAIL
exit status 1
FAIL    github.com/pelletier/go-toml    0.004s
```

**Comment by pelletier** [comment]
Good catch, thanks!

**Comment by pelletier** [comment]
Looks like this has been fixed in v2! https://github.com/pelletier/go-toml/commit/78389c641a0c1d14657b0a33fbc8ee3565da4cc0

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
