### ISSUE TITLE
iterating children of tree with preserving their order 

### ISSUE THREAD

**Issue by kybin** [pelletier/go-toml#477]
For example, when I have following toml file.

```
[a]
x = 1
y = 2

[b]
x = 3
y = 4
```

I want to know easy way to get

```
var s []struct {
    name string
    x int
    y int
}
```

with s[0].name == "a" always?

Because `*toml.Tree.Keys` doesn't preserve the children's order, I cannot use it directly. Also I don't find any other iterating method for the tree.

For now, I made my own `orderedKeys(t *toml.Tree) []string` function which sorts the tree's keys by comparing their Line and Col. But I feel it is complicated.

Please let me know if there is a better way :)

**Comment by pelletier** [comment]
Hi! go-toml currently does not preserve order of appearance in the document. However this is a requirement for TOML v2: https://github.com/pelletier/go-toml/discussions/471

**Comment by kybin** [comment]
Ah, I see. 

Thank you for letting me know!
