### ISSUE TITLE
Support unmarshalling snake_case in toml to CamelCase in struct field?

### ISSUE THREAD

**Issue by makalaaneesh** [pelletier/go-toml#478]
Basically, I would want this to work:

```
package main

import (
	"fmt"
	"github.com/pelletier/go-toml"
)

func main(){
	type Postgres struct {
		UserName string
	}
	type Config struct {
		Postgres Postgres
	}

	doc := []byte(`
[Postgres]
user_name = "pelletier"`)

	config := Config{}
	toml.Unmarshal(doc, &config)
	fmt.Printf("username=[%s]", config.Postgres.UserName)
}

```

**Comment by pelletier** [comment]
Hi, you can achieve this with the struct tag `toml`:

```go
package main

import (
	"fmt"
	"github.com/pelletier/go-toml"
)

func main(){
	type Postgres struct {
		UserName string `toml:"user_name"`
	}
	type Config struct {
		Postgres Postgres
	}

	doc := []byte(`
[Postgres]
user_name = "pelletier"`)

	config := Config{}
	toml.Unmarshal(doc, &config)
	fmt.Printf("username=[%s]", config.Postgres.UserName)
}
```

outputs:

```
username=[pelletier]
```

**Comment by makalaaneesh** [comment]
Ah, sure, right! 

But, I guess toml's style is snake_case, and go's style is CamelCase, so I was thinking that it would be great if you could have this functionality by default. 

Thoughts?

**Comment by boreq** [comment]
> Ah, sure, right!
> 
> But, I guess toml's style is snake_case, and go's style is CamelCase, so I was thinking that it would be great if you could have this functionality by default.
> 
> Thoughts?

Those changes can't be introduced anymore without releasing a new major version as they would break the backward compatibility of this package. Additionally the current behaviour mirrors the behaviour of the `encoding/json` package. On top of that [TOML specification](https://toml.io/en/v1.0.0) doesn't list what the recommended format of keys is. What you are suggesting is only a convention.

**Comment by pelletier** [comment]
Technically go-toml already tries multiple variants of a key when unmarshaling:

https://github.com/pelletier/go-toml/blob/a2e52561804c6cd9392ebf0048ca64fe4af67a43/marshal.go#L776-L781

Now, that's a pattern I would like to retire in [go-toml v2](https://github.com/pelletier/go-toml/discussions/471). I see it going two ways:

1. Use either the field name (capitalized) or the `toml` tag. That would mirror the behavior of `encoding/json` (which has been a guiding rule of thumb for me) and [BurntSushi/toml](https://github.com/BurntSushi/toml) (which would make the transition easier).
2. Use a default transformation of the field name (snake_case, kebab-case?) or the `toml` tag. That would mirror [go-yaml/yaml](https://github.com/go-yaml/yaml)'s behavior, which is an other popular library to parse configuration files.

My current intuition is to go with 1., as it feels like it would cause the least amount of surprise for Go programmers, and would avoid the library favoring one style over an other (while still permitting the user to pick their own style using struct tags).

My current focus is on scoping and writing out POCs for go-toml v2. To get the most of my limited time I won't be making changes to v1 that are not bug fixes.
