### ISSUE TITLE
Can't unmarshal an array of strings to a slice of structs

### ISSUE THREAD

**Issue by livingsilver94** [pelletier/go-toml#484]
**Describe the bug**
I can't unmarshal an array of strings to a slice of structs. The error message is:

> (1, 1): Can't convert [1 2 3 100]([]interface {}) to a slice

The struct type has both `MarshalText` and `UnmarshalText` methods. The issue probably comes from the fact the `interface{}` type has no method, so the library cannot find `UnmarshalText`. The marshalling works, in fact.

**To Reproduce**
Code is here: https://play.golang.org/p/0EXUUdosKVZ, but I'll copypaste it here as well for redundancy:

```golang
package main

import (
	"fmt"
	"github.com/pelletier/go-toml"
	"strconv"
)

type Integer struct {
	Value int
}

func (i Integer) MarshalText() ([]byte, error) {
	return []byte(strconv.Itoa(i.Value)), nil
}
func (i *Integer) UnmarshalText(data []byte) error {
	fmt.Println("NEVER CALLED")
	conv, err := strconv.Atoi(string(data))
	if err != nil {
		return err
	}
	i.Value = conv
	return nil
}

type Config struct {
	Integers []Integer `toml:"integers"`
}

func main() {
	raw := []byte(`integers = ["1","2","3","100"]`)
	var cfg Config
	fmt.Println(toml.Unmarshal(raw, &cfg))
	fmt.Printf("%#v", cfg)
}
```

**Expected behavior**
The `Integer` instances in the slice should have values 1, 2, 3, 100.

**Versions**
 - go-toml: 1.8.1
 - go: 1.15.8
 - operating system: Fedora 33 (Linux)

**Comment by pelletier** [comment]
Hi! I'm focusing on building go-toml v2. The unmarshal portion of it is working reasonably well (it passes all the tests that the v1 version passes).

It seems like you use-case works over there => https://github.com/pelletier/go-toml/commit/7f016efe0331b53af8b1aae5a6f1f6609defc887.

If by any chance you can use this version it should work for you. I'm unlikely to look at what's wrong on v1, but I gladly accept patches for it!

**Comment by livingsilver94** [comment]
Thanks @pelletier, your message is much appreciated!
Nah I don't feel like providing a patch for v1 which is going to be deprecated anyway, I can perfectly use 7f016ef.

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
