### ISSUE TITLE
return error "incorrect date/time separation character:" when add new line after local date

### ISSUE THREAD

**Issue by For-ACGN** [pelletier/go-toml#494]
**Describe the bug**
return error "incorrect date/time separation character:" when add new line after local date

**To Reproduce**
```go
// ok
"foo = 2021-04-08"  

// error
`
foo = 2021-04-08
bar = 2021-04-08
`
```
v1.8.1 is ok, but v1.9.0 will return error

**Expected behavior**
not return error

**Versions**
 - go-toml: v1.9.0
 - go: go1.16.3
 - operating system: Windows

**Additional context**
no

**Comment by pelletier** [comment]
Which function are you using? do you mind posting a full snippet of code?

**Comment by For-ACGN** [comment]
> 
> 
> Which function are you using? do you mind posting a full snippet of code?

oh! I forgot to write it.  I use toml.Unmarshal()

**Comment by For-ACGN** [comment]
> 
> 
> Which function are you using? do you mind posting a full snippet of code?

```go
func TestTomlLocalDateWithNewLine(t *testing.T) {
    data:= `
foo = 2021-04-08
bar = 2021-04-08
`
    type s struct {
          Foo time.Time `toml:"foo"`
          Bar time.Time `toml:"bar"`
    }
    ss := new(s)
    err := toml.Unmarshal([]byte(data), ss)
    // err is not nil
}
```

**Comment by pelletier** [comment]
Thanks! Definitely a bug in the V1 parser. Given the focus on V2 I've fixed it there (https://github.com/pelletier/go-toml/commit/275e366c17446746c9cddae71147eaada7c08da5). If you're only using Unmarshal you can use that branch: `go get github.com/pelletier/go-toml/v2@v2-wip` + replace your import with `github.com/pelletier/go-toml/v2`.

I'm keeping this bug open in case someone has bandwidth to fix it in the v1 parser too (@AllenX2018 in case you're interested).

Out of curiosity, why not using `toml.LocalDate` to represent timezone-independent dates? (not that it would have helped in that case, the bug is in the v1 parser)

**Comment by For-ACGN** [comment]
I want to use two kinds of time at the same time. This is just a special case used in the project.

**Comment by oschwald** [comment]
We also ran into this when upgrading from 1.8.1 to 1.9.0.

**Comment by 89z** [comment]
I dont recommend using V2 either, as I just found a significant bug as well (linked above my comment). I dont know what the best option is at this point. Personally I am looking to see if any other decent TOML packages around, as this is getting frustrating.

**Comment by 89z** [comment]
https://github.com/pelletier/go-toml/issues/575

**Comment by 89z** [comment]
Looks like the other TOML package is being maintained again. This program works as expected:

~~~go
package main

import (
   "fmt"
   "github.com/BurntSushi/toml"
   "time"
)

var data = []byte(`hello = 2020-12-31
`)

func main() {
   var greet struct { Hello time.Time }
   toml.Unmarshal(data, &greet)
   fmt.Printf("%+v\n", greet) // {Hello:2020-12-31 00:00:00 -0500 -0500}
}
~~~

**Comment by pelletier** [comment]
Also works on go-toml/v2.

**Comment by 89z** [comment]
True, but because of #575 `go-toml/v2` is not an option for me.

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
