### ISSUE TITLE
Panic on newline in key-value

### ISSUE THREAD

**Issue by CT-Zer0** [pelletier/go-toml#507]
**Describe the bug**
Hi. While I was fuzzing package, I am encountered with the following panic.

> panic: unhandled token: "0ame" [recovered]
        panic: interface conversion: interface {} is *errors.errorString, not string

I believe that it is panicked with the input that contains "\n" byte. 

**To Reproduce**
My code is following and you can also find it in [here](https://play.golang.org/p/Mnad1Ss-WEU):

```
package main

import "github.com/pelletier/go-toml"

func main()  {
        data := []byte{'0','=','\n','0','a','m','e'}
        tree, err := toml.LoadBytes(data)
        if err != nil {
                if tree != nil {
                        panic("tree must be nil if there is an error")
                }
        }

}
```

**Expected behavior**
I think it should return an error or parse remaining part of the input after newline.
**Versions**
 - go-toml: 1.9.0 ( directly installed with go get github.com/pelletier/go-toml)
 - go: version: go1.16.3 linux/amd64
 - operating system: Ubuntu 20.04.1 LTS

**Additional context**
It is found by [go-fuzz](https://github.com/dvyukov/go-fuzz). I would like to thank you for effort and providing fuzzing harness.

**Comment by pelletier** [comment]
Thank you for reporting this (and fuzzing go-toml)!

Definitely seems like the parser is panicking instead of returning an error when encountering an (invalid) new line in a key-value definition. Thankfully this has been fixed on the v2 branch (https://github.com/pelletier/go-toml/commit/0537b928df6308cb546eb61d60f68602a3e0e32c). If the feature-set of v2 alpha is good enough for you I suggest you use that branch. Otherwise I happily take pull requests for fixes on v1.

**Comment by CT-Zer0** [comment]
Hi again,

I am not actively using go-toml. I found this package while I was looking for fuzzing target :) I am satisfied with your answer so you do not need to fix it on v1. You can close this issue whenever you want.

Thanks.

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
