### ISSUE TITLE
go-toml v1.9.0 did not recognize anonymous struct

### ISSUE THREAD

**Issue by Andrew-M-C** [pelletier/go-toml#508]
**Describe the bug**
it seemed that go-toml does not recognize anonymous struct, but `BurntSushi/toml` does.

**To Reproduce**

Go codes: 

```go
package main

import (
	"fmt"
	
	bToml "github.com/BurntSushi/toml"
	pToml "github.com/pelletier/go-toml"
)

var b = []byte(`title = "This is a title"`)

type text struct {
	head
}

type head struct {
	Title string `toml:"title"`
}

func main() {
	t1, t2 := text{}, text{}
	
	pToml.Unmarshal(b, &t1)
	bToml.Unmarshal(b, &t2)
	
	fmt.Println("ptoml title:", t1.Title)
	fmt.Println("btoml title:", t2.Title)
}
```

Output: 

```
ptoml title: 
btoml title: This is a title
```

**Expected behavior**

Expected output is:

```
ptoml title: This is a title
btoml title: This is a title
```

**Versions**
 - go-toml: v1.9.0
 - go 1.16.3
 - operating system: macOS

**Comment by pelletier** [comment]
Thank you for reporting this! You're correct, the behavior should be the same as BurntSushi's on this.

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
