### ISSUE TITLE
QueryExample don't work

### ISSUE THREAD

**Issue by zhuangsirui** [pelletier/go-toml#52]
`https://godoc.org/github.com/pelletier/go-toml#example-Query--QueryExample` not work

**Comment by pelletier** [comment]
Thanks for the feedback! It does seem that this example is broken. I will work on a fix for that issue. @eanderton any idea?

**Comment by pelletier** [comment]
@zhuangsirui just pushed a fix on master that should solve that issue. Let me know if you're encountering any other issue and feel free to reopen that issue if it is not fixed for you.

**Comment by zhuangsirui** [comment]
@pelletier Thx!
