### ISSUE TITLE
Documentation examples for tree.Query outdated

### ISSUE THREAD

**Issue by embik** [pelletier/go-toml#54]
I noticed the godoc documentation for `go-toml` is outdated or wrong (I'm not sure here). `(t *TomlTree) Query(query string)` returns `(*QueryResult, error)`, yet the documentation is featuring a single-value assignation, for example at [doc.go#L86](https://github.com/pelletier/go-toml/blob/master/doc.go#L86) and [doc.go#L204](https://github.com/pelletier/go-toml/blob/master/doc.go#L204). The first example says
```
result := tree.Query("$.foo.bar.baz")  // result is 'nil' if the path is not present
```
which is obviously not true (anymore). It could say something like this:
```
result, err := tree.Query("$.foo.bar.baz")  // err is an error if the path is not present
```

Thanks for creating `go-toml`!

**Comment by pelletier** [comment]
Thank you for the feedback! I've updated the documentation to reflect the current behavior. Feel free to reopen an issue if you feel like it requires more details or is still incorrect.
