### ISSUE TITLE
Don't stutter

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#55]
This would be a breaking change, but `toml.TomlTree` should be `toml.Tree`.

**Comment by pelletier** [comment]
I agree. This has been something that I've had in the back of my mind for a while now. That would be a massively breaking change – effectively impacting everybody using this library. Even though it would indeed be cleaner not to have the `Toml` prefix, I don't think it's worth breaking backward compatibility.

I'm open to any ideas to provide a smooth transition though.

**Comment by pelletier** [comment]
Closing: probably won't do it until I decided to break backward compatibility, if ever.

**Comment by pelletier** [comment]
@moorereason reopening this. I've made up my mind, and feel like we should change that for 1.0.
