### ISSUE TITLE
License / Copyright of localtime.go

### ISSUE THREAD

**Issue by lhinderberger** [pelletier/go-toml#553]
Hello go-toml maintainers,

I want to bring your attention to an issue about the licensing of go-toml.
While browsing go-toml's sourcecode, I noticed that the file "localtime.go" has a copyright statement claiming the code in the file was covered by the Apache License v2.0.

I think it would be good if this was mentioned in the README or the LICENSE file (preferably both), because the Apache License v2.0 has stricter conditions for redistribution than the MIT license (see Article 4 of the license). At the moment, one could get the impression that the entirety of go-toml is covered by the MIT license, when in fact is has Apache-licensed parts.

Also, the Apache License v2.0 states "You must cause any modified files to carry prominent notices stating that You changed the files". It appears you have made changes to "localtime.go" since copying it from the other repository - I'm not sure if the "Copied over" notice at the top of "localtime.go" is enough to satisfy that condition.

The same applies to "localtime_test.go".

This is currently keeping me from adopting go-toml in one of my projects.
Please consider adressing these issues.

Thank you and kind regards
Lucas Hinderberger

**Comment by pelletier** [comment]
Thank you for bringing this up! Never noticed the issue.

Here is an attempt at rectifying the situation for go-toml v1: https://github.com/pelletier/go-toml/pull/554. Would this work?
For go-toml v2, I am first going to see if it's possible to not include those files at all. If not, I'll apply a similar change.

**Comment by lhinderberger** [comment]
Thank you for your quick reply!
I have had a look at the linked PR and to me it looks good (but please mind that I'm a software engineer, not a lawyer).
Not including those files in v2 if possible seems like a good idea too 👍

**Comment by pelletier** [comment]
Cool. Don't have a lawyer around to check. This seems like a reasonable attempt to fix this issue. I merged the license change for v1, and will be working on v2 next.

**Comment by pelletier** [comment]
I have rewritten the implementation of Local* types without using the original code from Google (#558).

Closing this issue as I feel like it has been addressed. Let me know otherwise! Thank you again for flagging this.
