### ISSUE TITLE
Recursive table unmarshalling causes panic

### ISSUE THREAD

**Issue by nabetani** [pelletier/go-toml#555]
**Describe the bug**
Unmarshal TOML

```toml
I=1
[F]
I=2
[F.F]
I=3
[F.F.F]
I=4
```
to struct
```go
type Foo struct {
	I int
	F *Foo
}
```
cause panic, not error.

**Expected behavior**

Succeeds in unmarshal.

**Versions**
 - go-toml: version 618f0181ac76015c3efdaf8b8ab5a468293f6e82
 - go: version go1.16.3 darwin/amd64
 - operating system: macOS

**Comment by pelletier** [comment]
Thank you for catching this!

**Comment by pelletier** [comment]
Closing as https://github.com/pelletier/go-toml/pull/557 has been merged. If it doesn't solve it for you feel free to reopen this issue!

Thank you again!
