### ISSUE TITLE
Index out of range error in expect function

### ISSUE THREAD

**Issue by CT-Zer0** [pelletier/go-toml#561]
**Describe the bug**
Hi there. While I was fuzzing go-tomlv2, I am encountered with index out of range error. My test case is `s=[` and I have assumed that  parseValArray function doesn't check if '[' is the last element before performing parser.go:401 :

	b = b[1:]<br class="Apple-interchange-newline">

**To Reproduce**
This is my code (you can also find it in [here](https://play.golang.org/p/kC8VGSwimxB)) : 

```
package main

import(
"github.com/pelletier/go-toml/v2"
"fmt"
)

type MyConfig struct {
      Version int
      Name    string
      Tags    []string
}


func main(){


doc := `s=[`

var cfg MyConfig
err := toml.Unmarshal([]byte(doc), &cfg)
if err != nil {
      fmt.Println("error")
}
fmt.Println("version:", cfg.Version)
fmt.Println("name:", cfg.Name)
fmt.Println("tags:", cfg.Tags)
}
```

**Expected behavior**
parseValArray should control boundaries and special characters before performing.
**Versions**
 - go-toml: github.com/pelletier/go-toml/v2 v2.0.0-beta.3 h1:PNCTU4naEJ8mKal97P3A2qDU74QRQGlv4FXiL1XDqi4=
 - go: 1.16.5
 - operating system: e.g. Ubuntu 20

**Additional context**
This bug is found by offical [dev.fuzz](https://github.com/golang/go/tree/dev.fuzz)

**Comment by pelletier** [comment]
Good catch, thank you! Will look into it.

**Comment by pelletier** [comment]
This has been fixed by https://github.com/pelletier/go-toml/commit/40cfb6f45824f8f5cd16957894b5c42e10b65f6e!
