### ISSUE TITLE
Missing Makefile for v2

### ISSUE THREAD

**Issue by jotego** [pelletier/go-toml#563]
I am trying to install v2, but it cannot be retrieved by the `go get` command. So I looked into compiling it, but it seems to miss a Makefile too. I can see a Makefile for version 1.

Could you add a Makefile or installation instructions?

Thank you

**Comment by pelletier** [comment]
Hi! go-toml uses the standard go modules system. There is no need for a Makefile to use the library. Just import `github.com/pelletier/go-toml/v2` and `go` will take care of downloading and compiling the library as necessary ([README](https://github.com/pelletier/go-toml/tree/v2#import)).

Let's get to the bottom of the discussion here https://github.com/pelletier/go-toml/discussions/562. If we find something is broken with the library we will then open an issue.

Thank you

**Comment by jotego** [comment]
Understood. Thank you.
