### ISSUE TITLE
v2 miss Local Time parse 

### ISSUE THREAD

**Issue by kkHAIKE** [pelletier/go-toml#566]
**Describe the bug**
v2 not support Local Time decode

**To Reproduce**
```
var m map[string]interface{}
err := toml.Unmarshal([]byte(`
[a]
a = 07:32:00
`), &m)
fmt.Println(m, err)
```

**Expected behavior**
get correct result

**Versions**
 - go-toml: 618f018
 - go: 1.16.5
 - operating system: macOS

**Additional context**
```
date-time      = offset-date-time / local-date-time / local-date / local-time
partial-time   = time-hour ":" time-minute ":" time-second [ time-secfrac ]
local-time = partial-time
```
https://github.com/pelletier/go-toml/blob/f6b38c33b7fe522e9c5539f66bd8966ce0006ac6/parser.go#L894-L902

**Comment by pelletier** [comment]
@kkHAIKE since https://github.com/pelletier/go-toml/pull/567 has been merged, is this issue fully resolved for you?
