### ISSUE TITLE
  Issue found by Svace static analyzer

### ISSUE THREAD

**Issue by vvdvortsova** [pelletier/go-toml#569]
Hello
This warning found with the Svace.
Using a variable follow after comparison with nil can lead to "panic in panic" in raiseError(..).
https://github.com/pelletier/go-toml/blob/8e44986c28d58aefff6125e52814ed1eb7eb0a6a/parser.go#L453
https://github.com/pelletier/go-toml/blob/8e44986c28d58aefff6125e52814ed1eb7eb0a6a/parser.go#L454
follow is dereferenced
https://github.com/pelletier/go-toml/blob/8e44986c28d58aefff6125e52814ed1eb7eb0a6a/parser.go#L27

**Comment by pelletier** [comment]
Thank you for the the report! Do you know if this issue is also present on the v2 branch? I'm happy to get a patch for v1, but I won't be fixing it personally.

**Comment by vvdvortsova** [comment]
This issue isn't present on the v2 branch.
There are the same issues for v1: 
in parseInlineTable()
https://github.com/pelletier/go-toml/blob/8e44986c28d58aefff6125e52814ed1eb7eb0a6a/parser.go#L410
in parseArray()
https://github.com/pelletier/go-toml/blob/8e44986c28d58aefff6125e52814ed1eb7eb0a6a/parser.go#L466
in assume(typ tokenType)
https://github.com/pelletier/go-toml/blob/8e44986c28d58aefff6125e52814ed1eb7eb0a6a/parser.go#L45

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
