### ISSUE TITLE
struct fields ignored by Decoder if declared after a slice

### ISSUE THREAD

**Issue by fxj-github** [pelletier/go-toml#573]
**Describe the bug**

Struct fields ignored by Decoder if declared after a slice.
Use 'config' has no problem.

**To Reproduce**
```
package main

import (
        "fmt"
        "bytes"
        "os"

        toml "github.com/pelletier/go-toml"
)

type address struct {
        Ip string `toml:"ip"`
        Port int `toml:"port"`
}

type config struct {
        Name string `toml:"name"`
        Addrs []*address `toml:"addrs"`
}

type config_wrong struct {
        Addrs []*address `toml:"addrs"`
        Name string `toml:"name"`
}

func main() {
        var conf config_wrong
        conf.Name = "abc"
        addr := &address{Ip:"127.0.0.1", Port:10000}
        conf.Addrs = append(conf.Addrs, addr)

        buf := new(bytes.Buffer)

        enc := toml.NewEncoder(buf)
        enc.Order(toml.OrderPreserve)
        if err := enc.Encode(&conf); err != nil {
                fmt.Printf("Encode: %v\n", err)
                os.Exit(1)
        }

        fmt.Printf("%s\n", buf.String())

        dec := toml.NewDecoder(buf)
        dec.Strict(false)
        var c config_wrong
        if err := dec.Decode(&c); err != nil {
                fmt.Printf("Decode: %v\n", err)
                os.Exit(1)
        }
        fmt.Printf("%s\n", c.Name)
        if c.Name == "" {
                fmt.Printf("BUG: c.Name should not be null!\n")
        }
}
```
**Expected behavior**
Whether use 'config' or 'config_wrong', c.Name should be decoded correctly.

**Versions**
 - go-toml: 1.9.3
 - go:1.16.7
 - operating system: Linux

**Comment by moorereason** [comment]
This looks like a bug in go-toml v1 when encoding with `OrderPreserve`.  The following encoding is wrong:

```toml
[[addrs]]
  ip = "127.0.0.1"
  port = 10000
name = "abc"
```
`name` must be rendered before the table.

But having said that, I would [recommend using v2](https://github.com/pelletier/go-toml#development-status) if you're able.  v2 doesn't exhibit this issue.  v2 also defaults to order preservation with strict mode enabled.

**Comment by fxj-github** [comment]
>>> name must be rendered before the table.
But if 'name' needs to be after 'addrs' in .toml file,  what can I do? Thanks.

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
