### ISSUE TITLE
reflect.Value.Set using unaddressable value

### ISSUE THREAD

**Issue by 89z** [pelletier/go-toml#575]
Using this file:

https://static.rust-lang.org/dist/channel-rust-stable.toml

and this program:

~~~go
package main

import (
   "github.com/pelletier/go-toml/v2"
   "os"
)

func main() {
   f, err := os.Open("channel-rust-stable.toml")
   if err != nil {
      panic(err)
   }
   defer f.Close()
   var dist struct {
      Pkg map[string]struct {
         Target map[string]struct {
            XZ_URL string
         }
      }
   }
   toml.NewDecoder(f).Decode(&dist)
}
~~~

I get this result:

~~~
panic: reflect: reflect.Value.Set using unaddressable value
~~~

Seems every single `v2` produces a `panic`, while `v1.9.3` works as expected.

**Comment by 89z** [comment]
https://github.com/gohugoio/hugo/issues/7799

**Comment by 89z** [comment]
https://github.com/pelletier/go-toml/issues/494

**Comment by 89z** [comment]
Looks like the other TOML package is being maintained again. Using the exact same program, but with this package works as expected:

https://github.com/BurntSushi/toml

**Comment by pelletier** [comment]
Thank you for reporting this bug! I'll take a look when I get a chance.

**Comment by 89z** [comment]
https://github.com/pelletier/go-toml/pull/576
