### ISSUE TITLE
tree level changed after writing toml tree to a file or printing on console 

### ISSUE THREAD

**Issue by prakashmirji** [pelletier/go-toml#577]
**Describe the bug**

I am trying to read/load the toml configuration file into object and doing some checks of the key and then adding new keys and then finally writing back to a file. After writing back to file ( or even console), I see the tree keys are messed ( tree kind of expanded).

For example, 

original toml file ( part of it )
```
[timeouts]
        "io.containerd.timeout.shim.cleanup" = "5s"
        "io.containerd.timeout.shim.load" = "5s"
        "io.containerd.timeout.shim.shutdown" = "3s"
        "io.containerd.timeout.task.state" = "2s"
```

After updating and writing back, it looks like ( part of the file)
```
[timeouts]

  [timeouts.io]

    [timeouts.io.containerd]

      [timeouts.io.containerd.timeout]

        [timeouts.io.containerd.timeout.shim]
          cleanup = "5s"
          demo = "prakash"
          load = "5s"
          shutdown = "3s"

        [timeouts.io.containerd.timeout.task]
          state = "2s"
```

**To Reproduce**
Steps to reproduce the behavior. Including TOML files.

here is the sample code to reproduce

```
package main

import (
	"github.com/pelletier/go-toml"
	log "github.com/sirupsen/logrus"
	"io/ioutil"
)

func main() {
	b, err := ioutil.ReadFile("config_test.toml") // unzip the attached zip file
	if err != nil {
		log.Errorf("failed to read file, error: %v", err)
	}
	content := string(b)
	newConfig, _ := toml.Load(content)
	newConfig.Set("timeouts.io.containerd.timeout.shim.demo", "prakash")
	
	str, _ := newConfig.ToTomlString()

	log.Infof("file content: %s\n", str)
	
}
```
Attached is the toml file  ( by the way, it is a default contained config.toml file)

**Expected behavior**
A clear and concise description of what you expected to happen, if other than "should work".

toml file tree should not be changed after editing. See above

**Versions**
 - go-toml: version (or git sha)
 - go: version
 - operating system: e.g. macOS, Windows, Linux

go-toml v1.9.3
go 1.16
macOS and Linux

**Additional context**
Add any other context about the problem here that you think may help to diagnose.

Our use case to edit the container config.toml and add new keys based on the requirement. If config.toml file format is charged , then contained process fails to load the configuration. Containerd throws this error message

containerd: toml: cannot load TOML value of type map[string]interface {} into a Go string

The question
[config_test.toml.zip](https://github.com/pelletier/go-toml/files/7098713/config_test.toml.zip)
 is: how to write toml object back to file with a correct format as in original

**Comment by moorereason** [comment]
This is working as designed.  From the `*Tree.Set` godoc:

> Set an element in the tree. **Key is a dot-separated path (e.g. a.b.c).** Creates all necessary intermediate trees, if needed.

In order to avoid the dot-separated path parsing, use `*Tree.SetPath` instead:

```go
newConfig.SetPath([]string{"timeouts","io.containerd.timeout.shim.demo"}, "prakash")
```
Try this [playground](https://play.golang.org/p/k_60kon-JaU).

**Comment by prakashmirji** [comment]
Thank you for the quick response. It was so helpful. 'SetPath' solves the problem I was having. This saved me from going to python library for toml.

**Comment by pelletier** [comment]
Looks like the issue was solved! Please reopen if not.
