### ISSUE TITLE
v2: can't unmarshal to custom non-struct types?

### ISSUE THREAD

**Issue by samhza** [pelletier/go-toml#590]
**Describe the bug**
v2 can't unmarshal values to a custom type that isn't a struct

**To Reproduce**
```go
package main

import (
        "fmt"

        "github.com/pelletier/go-toml/v2"
)

type CustomType int

func main() {
        var cfg struct {
                Option CustomType `toml:"option"`
        }
        err := toml.Unmarshal([]byte("option = 42"), &cfg)
        if err != nil {
                panic(err)
        }
        fmt.Println(cfg.Option)
}
```

**Expected behavior**
The program prints `42` as it would on v1.
**Actual Behavior**
```panic: reflect.Set: value of type int is not assignable to type main.CustomType```
**Versions**
 - `github.com/pelletier/go-toml/v2 v2.0.0-beta.3.0.20210908000859-a0d685d4822f`
 - `go version go1.16.7 linux/amd64`

**Comment by pelletier** [comment]
Thanks for reporting! This is probably in the same category as https://github.com/pelletier/go-toml/issues/571. Will take a look.

**Comment by pelletier** [comment]
This should be fixed in the latest commit of v2 (https://github.com/pelletier/go-toml/commit/ee9b902222c33ad156960573001c3aae9bcc963c). Feel free to reopen if it's not!
