### ISSUE TITLE
"omitempty" support for v2

### ISSUE THREAD

**Issue by qinabu** [pelletier/go-toml#597]
Please, don't forget to add support the omitempty tag option for compatibility.

```
type Some struct {
    Name `toml:"name,omitempty"`
}
```

As a result on v2.0.0-beta.3:
```
'name,omitempty' = ''
```

**Comment by pelletier** [comment]
Thank you for the reminder!

**Comment by pelletier** [comment]
Implemented in https://github.com/pelletier/go-toml/commit/0d20a845236c457da67e2e92d0888dae14865656. Thank you!
