### ISSUE TITLE
v2: allow lowercase 't' and 'z' in date-time

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#600]
**Describe the bug**
[RFC3399](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) allows for lowercase 't' and 'z' in date-time:

> NOTE: Per ABNF and ISO8601, the "T" and "Z" characters in this syntax may alternatively be lower case "t" or "z" respectively.

v2 currently rejects the lowercase syntax:

```
toml: expected newline but got U+0074 't'
toml: expected newline but got U+007A 'z'
```

**To Reproduce**
https://play.golang.org/p/1ONC1N7NhEI
```go
toml.Unmarshal([]byte("a=1979-05-27t00:32:00Z"), &v)
```

https://play.golang.org/p/4rrFAu71U83
```go
toml.Unmarshal([]byte("a=1979-05-27T00:32:00z"), &v)
```

**Expected behavior**
These should be parsed as valid date-time values.

**Versions**
 - go-toml: v2 ee9b902222c33ad156960573001c3aae9bcc963c
 - go version go1.17 linux/amd64

**Additional Context**

Causes test `valid/datetime/datetime` in [toml-test](https://github.com/BurntSushi/toml-test) to fail.

**Comment by pelletier** [comment]
Fixed in https://github.com/pelletier/go-toml/pull/601

Thank you for the report and the patch!
