### ISSUE TITLE
Marshaling not working as intended?

### ISSUE THREAD

**Issue by Gaz492** [pelletier/go-toml#612]
**Describe the bug**
Trying to generate a config file with prefilled options but its not creating the options.

**To Reproduce**
```go
type (
	Config struct {
		Database DB `toml:"Database"`
	}

	DB struct {
		hostname string `toml:"hostname"`
		port string `toml:"port"`
		name string `toml:"name"`
		password string `toml:"password"`
	}
)

rawConf := Config{
			Database: DB{
				hostname: "localhost",
				port: "3306",
				name: "example",
				password: "",
			},
		}
		genConf, err := toml.Marshal(rawConf)
```
Only outputs [Database]

**Expected behavior**
Using the code above I would expect it to output the following
```toml
[Database]
hostname = 'localhost'
port = '3306'
name = 'example'
password = ''
```

**Versions**
 - go-toml: v2.0.0-beta.3
 - go: 1.16.5
 - operating system: macos

**Additional context**

**Comment by pelletier** [comment]
It is working as intended: it only marshals exported fields.`DB` only have private fields, so they are not marshaled. This is the same behavior has `encoding/json`.

**Comment by Gaz492** [comment]
> 
> 
> It is working as intended: it only marshals exported fields.`DB` only have private fields, so they are not marshaled. This is the same behavior has `encoding/json`.

Apologies, this is what I get for programming while tired. Just needed that second set of eyes to point that out :P
