### ISSUE TITLE
Decoding doesn't always return DecodeError

### ISSUE THREAD

**Issue by samhza** [pelletier/go-toml#625]
README.md says DecodeError is returned when decoding errors occur, and the DecodeError example on the godoc does a type assertion directly to a DecodeError. I believe this is a mistake in the documentation, and could lead to someone assuming Decode always returns a DecodeError and making a type assertion like the one in the example that could panic. This should be clarified and the example should use `errors.As` instead.

**Comment by pelletier** [comment]
Good call. Thanks for the feedback!

**Comment by pelletier** [comment]
Added clarifications about errors returned and fixed the example using DecodeError: https://github.com/pelletier/go-toml/commit/d58eb50ebfb929b84ef2af730b2f8503aa4a25fb

Feel free to reopen if you think it is unclear.
