### ISSUE TITLE
Don't allow carriage return inside basic string

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#651]
**Describe the bug**
Given `"\r"="\r"`, go-toml accepts the key and value as valid.

**To Reproduce**
https://play.golang.org/p/qT4YyCSwnfb
```go
toml.Unmarshal([]byte("\"\r\"=\"\r\""), &v)
```

**Expected behavior**
Expect to receive an error on invalid control character in a basic string.

**Versions**
 - go-toml: 85c065898423299fdfb0d63ab70ef77217f7e129
 - go version devel go1.18-6294207a1c7 Tue Oct 19 15:03:39 2021 +0000 linux/amd64

**Additional context**
Found while doing differential fuzzing against BurntSushi.

**Comment by pelletier** [comment]
Thank you! Should be fixed by https://github.com/pelletier/go-toml/commit/3dbca20bc9c5b4256ebf981b879be5841a9a84fb
