### ISSUE TITLE
Limit control characters in comments

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#653]
**Describe the bug**
Given the input `# this is a test\ra=1`, this package decodes the line as a valid comment.

The current [`scanComment` implementation](https://github.com/pelletier/go-toml/blob/3dbca20bc9c5b4256ebf981b879be5841a9a84fb/scanner.go#L141) doesn't really check for invalid ascii control characters.

**To Reproduce**
https://play.golang.org/p/yaj7bOEzjJQ
```go
toml.Unmarshal([]byte("# this is a test\ra=1"), &v)
```

**Expected behavior**
I expected to see an error.  `\r` is not an allowed control character for comments.

**Versions**
 - go-toml: 3dbca20bc9c5b4256ebf981b879be5841a9a84fb
- go version go1.17.1 linux/amd64

**Additional context**
Found while doing differential fuzzing against BurntSushi.  Interestingly, BurntSushi also doesn't return an error, but it parses the line as `a=1`.

**Comment by pelletier** [comment]
The current `scanComment` implementation actually calls `utf8ValidNext`, which ensures no control character is present through `invalidAscii` https://github.com/pelletier/go-toml/blob/3dbca20bc9c5b4256ebf981b879be5841a9a84fb/utf8.go#L143-L145

_except_ for `\t`, `\r`, and `\n`.

**Comment by pelletier** [comment]
Should be fixed by https://github.com/pelletier/go-toml/commit/74d21b367fcda2bf00d80d346e487754deba4938. Thank you!
