### ISSUE TITLE
Date detection bug

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#655]
**Describe the bug**
Given `a=19#9-`, go-toml complains:  "Error decoding TOML: toml: dates are expected to have the format YYYY-MM-DD"

**To Reproduce**
https://play.golang.org/p/znORfqPgEzS
```go
toml.Unmarshal([]byte("a=19#9-"), &v)
```

**Expected behavior**
The result should be `a=19`.

**Versions**
 - go-toml: 6617e7e73d2f2b7f460ef2b0b0fa03a18fe9396a
 - go version go1.17.1 linux/amd64

**Additional context**
Found while doing differential fuzzing against BurntSushi.

**Comment by pelletier** [comment]
Should be fixed by https://github.com/pelletier/go-toml/commit/11f789ef115c6de5b7f7a0b01fc7a24db2fd1b55. Thank you!
