### ISSUE TITLE
Duplicate key allowed in inline table

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#658]
**Describe the bug**
Given `e={b=1,b=4}`, go-toml returns the following (using `gotoml-test-decoder`):

```
{
  "e": {
    "b": {
      "type": "integer",
      "value": "4"
    }
  }
}
```

**To Reproduce**
https://play.golang.org/p/by7ih3epoCp

```go
toml.Unmarshal([]byte("e={b=1,b=4}"), &v)
```

**Expected behavior**
I expected an error.  The TOML spec says:

> Defining a key multiple times is invalid.

BurntSushi returns an error of `Key 'e.b' has already been defined`.

**Versions**
 - go-toml: 11f789ef115c6de5b7f7a0b01fc7a24db2fd1b55
 - go version devel go1.18-6294207a1c7 Tue Oct 19 15:03:39 2021 +0000 linux/amd64

**Additional context**
Found while doing differential fuzzing against BurntSushi.

**Comment by moorereason** [comment]
Once this is fixed, we can regen the toml-test files to include https://github.com/BurntSushi/toml-test/pull/93.

**Comment by pelletier** [comment]
Started working on this, but realized there is some part of the spec that is unclear to me: https://github.com/toml-lang/toml/pull/848#issuecomment-962715054.

Let me know if you have any thoughts on how we should handle dotted keys in inline tables!

**Comment by pelletier** [comment]
👍🏻 Went with that interpretation until they chime in.

**Comment by pelletier** [comment]
Regenerated the toml-test files to include the new test. Let me know if i've missed anything.
