### ISSUE TITLE
Duplicate key allowed in inline table inside an array

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#662]
**Describe the bug**
Similar to #658

Given `a=[{b=1,b=2}]`, go-toml returns the following (using `gotoml-test-decoder`):
```
{
  "a": [
    {
      "b": {
        "type": "integer",
        "value": "2"
      }
    }
  ]
}
```

**To Reproduce**
https://play.golang.org/p/DxoAkvnWJLI
```go
toml.Unmarshal([]byte("a=[{b=1,b=2}]"), &v)
```

**Expected behavior**
I expected an error about duplicate keys within the inline table.

**Versions**
 - go-toml: 644515958cc34d8ce4c2974197b306b99ec651b7
 - go version go1.17.1 linux/amd64

**Additional context**
Found while doing differential fuzzing against BurnstSushi.

**Comment by pelletier** [comment]
Should be fixed by https://github.com/pelletier/go-toml/commit/f27a07d31ac7607aa4863e32d5a0f68327a50f14. As far as I know only inline tables and arrays are containers in values, so that should be the end of it 😅

**Comment by moorereason** [comment]
If not, the fuzzer will probably find it!  😄
