### ISSUE TITLE
Multiline string parsing issue

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#664]
**Describe the bug**
Given `0="""\""""""`, `gotoml-test-decoder` returns:
```
{
  "x": {
    "type": "string",
    "value": "\"\"\""
  }
}
```

**To Reproduce**
https://play.golang.org/p/8ecfb_4Woic
```go
toml.Unmarshal([]byte("0=\"\"\"\\\"\"\"\"\"\""), &v)
```
yields:
```
result:  map[string]interface {}{"0":"\"\"\""}
```

**Expected behavior**
I expected an error since we have too many double-quotes at the end of the string.

BurntSushi returns `Error decoding TOML: Near line 1 (last key parsed '0'): unexpected '""""""'`

**Versions**
 - go-toml: f27a07d31ac7607aa4863e32d5a0f68327a50f14
 - go version go1.17.1 linux/amd64

**Additional context**
Found while doing differential fuzzing against BurnstSushi.

**Comment by pelletier** [comment]
Actually, isn't this supposed to be valid? 

This is the example from the spec:

```toml
str6 = """Here are fifteen quotation marks: ""\"""\"""\"""\"""\"."""
```

The pattern `\"""` seems to be accepted. The first `"` is escaped, and the quotes two and three are following

> You can write a quotation mark, or two adjacent quotation marks, anywhere inside a multi-line basic string.

**Comment by moorereason** [comment]
I think you're right.  I wasn't aware of that allowance in the spec and didn't think to even look for it.
