### ISSUE TITLE
Issue parsing duplicate keys

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#666]
**Describe the bug**
Two inputs with duplicate keys give invalid or odd results:

Given `a={}\na={}`, `gotoml-test-decoder` returns:
```
{
  "a": {}
}
```
Given `a=1\na=2`, `gotoml-test-decoder` returns:
```
Error decoding TOML: toml: expected a to be a table, not a value
```

**To Reproduce**
https://play.golang.org/p/Z3TgOrkhs5B
```go
toml.Unmarshal([]byte("a={}\na={}"), &v)
```

https://play.golang.org/p/J59RodyIGaf
```go
toml.Unmarshal([]byte("a=1\na=2"), &v)
```

**Expected behavior**
In both cases, I expected to see an error about duplicate keys in the "root" table.

While we get an error with the second input, the error is confusing.

**Versions**
 - go-toml: 2dbd29a56531bb11606795f9098ec590c4d5acac
 - go version go1.17.1 linux/amd64

**Additional context**
Found while doing differential fuzzing against BurnstSushi.

**Comment by pelletier** [comment]
Should be fixed by https://github.com/pelletier/go-toml/commit/4dff8eaa4df42581d7bf14b90363c759fe58d9d9. Filed https://github.com/pelletier/go-toml/issues/668 to provide better errors for duplicates tracking.
