### ISSUE TITLE
Disallow bare carriage return in multiline basic string

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#674]
**Describe the bug**
Given a multiline basic string containing a bare carriage return (ie. `a="""\r"""`), no error is returned.

**To Reproduce**
https://go.dev/play/p/QBjpOdzItKV
```go
toml.Unmarshal([]byte("a=\"\"\"\r\"\"\""), &v)
```

**Expected behavior**
I expected the bare `\r` to return an error since it's not followed by a `\n` character.

**Versions**
 - go-toml: 64fe47161f06327328066634453811622f664583
 - go version go1.17.3 linux/amd64

**Additional context**
Found while doing differential fuzzing against [toml.dart](https://github.com/just95/toml.dart). :dart:

**Comment by pelletier** [comment]
Should be fixed in https://github.com/pelletier/go-toml/commit/1b5a25c0ef351113c169c72a61c1522cd7c3d788. Thank you!
