### ISSUE TITLE
Disallow bare carriage return in multiline literal string

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#685]
**Describe the bug**
Similar to #674.

Given a multiline literal string containing a bare carriage return (ie. `a='''\r'''`), no error is returned.

**To Reproduce**
https://go.dev/play/p/ME9tg8xqQpp
```go
toml.Unmarshal([]byte("a='''\r'''"), &v)
```

**Expected behavior**
I expected the bare `\r` to return an error since it's not followed by a `\n` character.

**Versions**
 - go-toml: b226db6a2950c2b2d89884d09cbca2d8d3119348
 - go version go1.17.3 linux/amd64

**Additional context**
Found while doing differential fuzzing against [toml.dart](https://github.com/just95/toml.dart). :dart:

**Comment by pelletier** [comment]
Should be fixed in https://github.com/pelletier/go-toml/commit/ede644560890e63f58ed159bab1a28ed7f3f888b. Thanks again for finding all those!
