### ISSUE TITLE
Fix zone offset in time parser

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#690]
**Describe the bug**
Given `0=0000-01-01 00:00:00+27000`, go-toml doesn't return an error on the time zone offset.
```
$ echo "0=0000-01-01 00:00:00+27000" | gotoml-test-decoder
{
  "0": {
    "type": "datetime",
    "value": "0000-01-01T00:00:00+27:00"
  }
}
```

**To Reproduce**
https://go.dev/play/p/fES37UrI64-
```go
toml.Unmarshal([]byte("0=0000-01-01 00:00:00+27000"), &v)
```

**Expected behavior**
I expected to see an error on invalid time zone offset since it has 5 digits instead of the max of 4.  Per RFC3339/ISO8601 ABNF:
```abnf
time-hour         = 2DIGIT ; 00-24
time-minute       = 2DIGIT ; 00-59
time-numoffset    = ("+" / "-") time-hour [[":"] time-minute]
```

**Versions**
 - go-toml: 4c7a337083984897cf20bd8fcfcf3525b19f4a55
- go version go1.17.3 linux/amd64

**Additional context**
Found while doing differential fuzzing against `toml-dart`.

**Comment by pelletier** [comment]
Should be fixed in https://github.com/pelletier/go-toml/commit/3990899d7eec45790be0f4a5344e387a89098181.
