### ISSUE TITLE
Disallow modification of inline tables

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#701]
**Describe the bug**
Given the following TOML documents, this package doesn't return an error:

```toml
a={}
[a.b]
z=0
```

```toml
a={}
[[a.b]]
z=0
```

**To Reproduce**
https://go.dev/play/p/yT6-iD8Y4SH
```go
toml.Unmarshal([]byte("a={}\n[a.b]\nz=0"), &v)
```

**Expected behavior**
Return an error since `a` cannot be modified.  From [the TOML spec](https://toml.io/en/v1.0.0#inline-table):

> Inline tables are fully self-contained and define all keys and sub-tables within them. Keys and sub-tables cannot be added outside the braces.

**Versions**
 - go-toml: 8bbb51947738eee5a28e59554425c89bbb962a9f
 - go version go1.17.3 linux/amd64

**Additional context**
Found while doing differential fuzzing against toml-dart.

**Comment by pelletier** [comment]
Wrote those checks thinking that any key could be set from anywhere, as that was my understanding at the time. Good news is that we maybe able to not have to retain as much memory.

**Comment by pelletier** [comment]
Should be fixed by https://github.com/pelletier/go-toml/commit/facb2b13e8195a69a68307c24cd8ed6610446a18. Thanks!
