### ISSUE TITLE
Error on multiline basic string backslash trimming with CRLF

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#708]
**Describe the bug**
`go-toml` returns an error on a multiline basic string with an unescaped backslash followed by CRLF.  This sequence should be valid.

**To Reproduce**
https://go.dev/play/p/3aIPpYSTpxO
```go
toml.Unmarshal([]byte("0=\"\"\"\\\r\n\"\"\""), &v)
```

**Expected behavior**
I expect the parser to recognize the `\r\n` sequence as a whitespace character to be trimmed.  The TOML spec:

> For writing long strings without introducing extraneous whitespace, use a "line ending backslash". When the last non-whitespace character on a line is an unescaped `\`, it will be trimmed along with all whitespace (including newlines) up to the next non-whitespace character or closing delimiter.

**Versions**
 - go-toml: 5cbdea6192d0413a1b556dc4db7078d9eb99165c
 - go version go1.17.5 linux/amd64

**Additional context**
Also submitted a PR to `toml-test` to include this case:  https://github.com/BurntSushi/toml-test/pull/105

Found while doing differential fuzzing against [`toml.dart`](https://github.com/just95/toml.dart). :dart:

**Comment by pelletier** [comment]
Should be fixed in https://github.com/pelletier/go-toml/commit/177b4a5e538159e01f2d41ae566d4e4751ed4d04. Thank you!
