### ISSUE TITLE
why are there pointer receiver methods on toml.Position?

### ISSUE THREAD

**Issue by nhooyr** [pelletier/go-toml#71]
Every function returns a value of `toml.Pointer`, not a pointer to `toml.Pointer` which makes calling them very awkward.

As in you can't do this:
```go
log.Fatalf("password must be a string: %s", t.GetPosition("password"))
```

You must instead do:
```go
p := t.GetPosition("password")
log.Fatalf("password must be a string: %s", &p)
```

This is because the `Position.String()` method is defined with a pointer receiver, and thus not part of the method set of the value struct.

**Comment by pelletier** [comment]
No particular reason. Patches welcome :)
