### ISSUE TITLE
Implement fmt.Stringer

### ISSUE THREAD

**Issue by sambooo** [pelletier/go-toml#72]
TomlTree currently has a ToString method but no String method which means it doesn't implement the standard interface for stringifying. I'm looking to be able to define an interface:
```go
type Config interface {
	Get(key string) interface{}
	Set(key string, value interface{})
	fmt.Stringer
}
```
and use TomlTree as the implementation.

**Comment by pelletier** [comment]
Thank you for your contribution! PR merged.
