### ISSUE TITLE
Detect leading zero on positive float

### ISSUE THREAD

**Issue by moorereason** [pelletier/go-toml#734]
**Describe the bug**
Given a float such as `0=+0_0.0`, `go-toml` accepts the input as valid.
```
$ echo -n "0=+0_0.0" | gotoml-test-decoder
{
  "0": {
    "type": "float",
    "value": "0"
  }
}
```

**To Reproduce**
https://go.dev/play/p/EDKOatLs5WA
```go
toml.Unmarshal([]byte("0=+0_0.0"), &v)
```

**Expected behavior**
Expected to see an error about leading zero on a float number.

**Versions**
 - go-toml: v2 e83cf535f54a66d986ff3c62753a98bbf51ba06d
 - go version go1.17.5 linux/amd64

**Additional context**
Found while doing differential fuzzing against [`tomlplusplus/v3`](https://github.com/marzer/tomlplusplus/tree/v3).

**Comment by pelletier** [comment]
Thanks!
