### ISSUE TITLE
UnmarshalText error readability

### ISSUE THREAD

**Issue by thierry-f-78** [pelletier/go-toml#737]
**Describe the bug**

I use go-toml to parse a configuration file. The parsing errors are shown by a system administrator and not by a developper.

I implement a Marshaller to Unmarshal some type (time.Duration in example). When my duration is wring, I read this message:

```
2| 	duration = "##fdsf"
 |             ~~~~~~~~ error calling UnmarshalText: invalid duration "##fdsf"
3| 	
```

The administrator read an error strating by "error calling UnmarshalText", but this string is related to program internal behavior. The administrator dont care about this information. This information could be perturbated by this information and could contact software support.

**To Reproduce**

https://go.dev/play/p/6YvcBbolsFu

**Expected behavior**

I suggest when the marshaller return a error, the error is reported as-is (without prefix).

If you're ok, I could write a PR

**Versions**
 - go-toml: Go playground checkouted version, I suppose the last github version fed1464
 - go: Go playground version
 - operating system: Go playground OS

**Comment by pelletier** [comment]
Sorry for the wait! I think that's a reasonable change. I am a little worried about the loss of information for a programmer who would be implementing unmarshaling for their own types, but at that point they probably know where the issue may be coming from. Feel free to open a PR!

**Comment by pelletier** [comment]
Removed in [f5cc8c4](https://github.com/pelletier/go-toml/commit/f5cc8c49eb6f4ea5635e1e9df82fb418c7482d9b). Let me know if that doesn't work for you!
