### ISSUE TITLE
Decode: incorrect table redefinition error 

### ISSUE THREAD

**Issue by jmooring** [pelletier/go-toml#739]
> table bar already exists

```text
[foo.bar.baz]
wibble = 'wobble'

[foo]

[foo.bar]
huey = 'dewey'
```

**Comment by jmooring** [comment]
Just to clarify, this is a regression.

**Comment by pelletier** [comment]
Thank you for the report! I think https://github.com/pelletier/go-toml/issues/703 was too aggressive in preventing table redefinition.

**Comment by pelletier** [comment]
This should be fixed as of https://github.com/pelletier/go-toml/commit/89d7b412d87493fafefc8cf0612fd0652bec374e. Let me know if you have any issue with it!
