### ISSUE TITLE
Missed position when decoding invalid zero-started number

### ISSUE THREAD

**Issue by arkoort** [pelletier/go-toml#742]
**Describe the bug**
When toml file contains invalid number, there's no position in the file reported.

**To Reproduce**
```echo 'qwe = 001' | tomll```

**Expected behavior**
```(1, 7): invalid base```
but reported:
```invalid base```

**Versions**
 - go-toml: version 1.8.1
 - go: 1.15.9-6
 - operating system: Linux Debian

**Additional context**
This version is distributed in Debian Testing

**Comment by pelletier** [comment]
Thanks for reporting the bug! As this is on the v1 branch, I won't be actively working on it, but gladly accept a patch! This report made me notice that v2's tomll doesn't report error lines anymore, which I'll track in a new issue.

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
