### ISSUE TITLE
type *toml.TomlTree has no field or method ToMap

### ISSUE THREAD

**Issue by snapo28** [pelletier/go-toml#75]
I get the next error using ToMap():
```Go
tree.ToMap undefined (type *toml.TomlTree has no field or method ToMap)
```

I'm implementing like the example in the other issue #53 
```Go
tree, _ := toml.LoadFile('myfile.toml')
myconfig := tree.ToMap()
```

And I'm trying to read the next file:
```TOML
[ignore]
file = [
		[["folder1"],["file", "tmp.txt", "*.cpp"]],
		[["folder2"],["*"]]
	]
```

**Comment by pelletier** [comment]
Do you know which revision you're using? I'm not having any issue with that file using `master`: https://gist.github.com/pelletier/fc54c335d21fabd7ea9b1cac99227dca

**Comment by snapo28** [comment]
I don't know what happened, I used the command:
```Go
go get github.com/pelletier/go-toml
``` 
In that point the code doesn't run, now is working but I had to download the code and put into my project manually.

**Comment by pelletier** [comment]
Weird. Closing as this seems solved. If you manage to reproduce the issue feel free to reopen.
