### ISSUE TITLE
Marshaling array table doesn't emit struct tag comment

### ISSUE THREAD

**Issue by gcstang** [pelletier/go-toml#774]
**Describe the bug**
Still no comment in v2.0.0 of the API, was supposed to be fixed here #595 

**To Reproduce**
Steps to reproduce the behavior. Including TOML files.
(Example Go File attached, gzipped so it would let me attach them)
- Create Go Object 
- Create instance set values
- toml.Marshal object instance
- write out the []byte

**Expected behavior**
Setting the toml comment should work on all array types
In example `[[scp]]` doesn't include it's comment

**Versions**
 - go-toml: v2.0.0
 - go: 1.17.9
 - operating system: macOS 12.3.1 on m1

**Additional context**
Add any other context about the problem here that you think may help to diagnose.
[main.go.gz](https://github.com/pelletier/go-toml/files/8654673/main.go.gz)
[go.sum.gz](https://github.com/pelletier/go-toml/files/8654674/go.sum.gz)
[go.mod.gz](https://github.com/pelletier/go-toml/files/8654675/go.mod.gz)
[demo.toml.gz](https://github.com/pelletier/go-toml/files/8654676/demo.toml.gz)

**Comment by pelletier** [comment]
Thank you for filing the issue.

Playground link to reproduce: https://go.dev/play/p/sLezx1tt0yR

**Comment by pelletier** [comment]
Should be fixed as of https://github.com/pelletier/go-toml/commit/627dade0c796e720205e26fc875d33db3e548122.
