### ISSUE TITLE
jsontoml transforms integer to floats

### ISSUE THREAD

**Issue by zupalex** [pelletier/go-toml#780]
Hi,

using latest version of jsontoml (2.0.1) I observe an unintended behaviour. Integers become float

e.g.
```bash
echo '{"test": 4}' | jsontoml
```

will output
```bash
test = 4.0
```

I did not find related issues about this surprisingly, sorry if I'm missing something obvious

**Comment by zupalex** [comment]
Actually after testing encoding/json in go playground I realized that it's the json package that decodes int as float64 so not much you can do on your side I guess. Closing this issue.

**Comment by YongBig** [comment]
I have this problem. How did you solve this problem?




> Actually after testing encoding/json in go playground I realized that it's the json package that decodes int as float64 so not much you can do on your side I guess. Closing this issue.
