### ISSUE TITLE
uint64 range limited by int64

### ISSUE THREAD

**Issue by jmank88** [pelletier/go-toml#781]
**Describe the bug**
Attempting to unmarshal a value a larger than `math.MaxInt64` results in a `value out of range` error from `strconv.ParseInt`, even when the target field is a `uint64`.

**To Reproduce**
https://go.dev/play/p/L_zgsE-vlAl

**Expected behavior**
I expected the full range of `uint64` values to be supported.

**Versions**
 - go-toml: v2.0.1
 - go: 1.18
 - operating system: Linux

**Comment by pelletier** [comment]
Thank you for reporting this!

**Comment by pelletier** [comment]
Merged https://github.com/pelletier/go-toml/commit/85bfc0ed5117cb316bbbcd9e65ecfcb95419be88. It prevents the asymmetry problem you pointed out by preventing uint64 > maxInt64 to be encoded. 

Thank you again for reporting since and driving the discussion to improve the library!
