### ISSUE TITLE
Provide pre-compiled binaries for Raspberry Pi

### ISSUE THREAD

**Issue by djmattyg007** [pelletier/go-toml#789]
It would be much appreciated if this project could provide pre-compiled binaries for the Arm v7 and Arm v8 (64-bit) architectures running on Linux. These are both super common in the single board computer world (eg. Raspberry Pis).

**Comment by pelletier** [comment]
Good idea! Will add arm and arm64 builds to the release system.

**Comment by pelletier** [comment]
Added arm and arm64 for Linux and Windows to the build, and released a new version with those binaries attached: https://github.com/pelletier/go-toml/releases/tag/v2.0.2.

**Comment by djmattyg007** [comment]
Thank you so much!
