### ISSUE TITLE
Support for passing values using enviorment variables

### ISSUE THREAD

**Issue by josepowera** [pelletier/go-toml#797]
Allow TOML to read some variables not from TOML file - but from using Enviorment variables. 
Similar to  https://docs.influxdata.com/telegraf/v1.21/administration/configuration/#set-environment-variables
or https://github.com/spf13/viper#working-with-environment-variables

This makes configurations in kubernetes enviorments much more easy.

**Comment by pelletier** [comment]
I believe interpolating environment variables in string values is outside the scope of go-toml. This can be accomplished outside of the library in various ways depending on what you need. Adding this feature to go-toml would increase the maintenance cost for no clear benefit.
