### ISSUE TITLE
Exellent error messages! Thanks a lot!

### ISSUE THREAD

**Issue by bep** [pelletier/go-toml#800]
I have been using go-toml v2 to handle config for a new side project I'm playing with, and the quality of the errors you return are real time-saver and makes this library a pleasure to use. I especially like the `StrictMissingError`.

```bash
         9| [replacements]
          |  ~~~~~~~~ cannot store a table in a slice
```

And yes, you can close this issue. Have a great weekend!

**Comment by pelletier** [comment]
Thank you @bep! Means a lot. I always appreciate your patience and kind feedback.
