### ISSUE TITLE
parse incorrect

### ISSUE THREAD

**Issue by 60ke** [pelletier/go-toml#817]
**Describe the bug**
parse result incorrect

**To Reproduce**
```go
package main

import (
	"fmt"
	"os"

	"github.com/pelletier/go-toml"
)

var tomlStrFalse = `
[[tm]]
  ip = "192.168.1.1"

tm-server = "127.0.0.1"
`
var tomlStrTrue = `
tm-server = "127.0.0.1"
[[tm]]
  ip = "192.168.1.1"
`

type TMConf struct {
	IP string `toml:"ip"`
}

type Config struct {
        TM     []TMConf `toml:"tm"`
	Server string   `toml:"tm-server"`
	
}

func main() {
	var conf1 Config
	var conf2 Config
	toml.Unmarshal([]byte(tomlStrTrue), &conf1)
	toml.Unmarshal([]byte(tomlStrFalse), &conf2)
	fmt.Println(conf1.Server, conf2.Server)
	f, _ := os.Create("./test.toml")
        defer f.Close()
	enc := toml.NewEncoder(f)
        enc.Order(toml.OrderPreserve)
	enc.Encode(conf1)
	

}

```

**Expected behavior**
`conf1` should same as `conf2`,or may `test.toml` should  include like `tm-server`'s value,but now `test.toml ` is:
```toml
[[tm]]
  ip = "192.168.1.1"
tm-server = "127.0.0.1"

```

**Versions**
 - go-toml: v1.9.5 h1:4yBQzkHv+7BHq2PQUZF3Mx0IYxG7LsP222s7Agd3ve8=
 - go: go1.19 darwin/arm64
 - operating system: macOS

**Comment by pelletier** [comment]
I don't think those two documents are equivalent. Indentation doesn't matter in TOML. The first document has `tm-server` as part of the first element of the `tm` array. The second document has it as an element at the root of the document.

**Comment by 60ke** [comment]
> ```go
> enc.Order(toml.OrderPreserve)
> ```

You are right，but if you use `enc.Order(toml.OrderPreserve)` to sort the second-element,and save to file, you will see that the key : `tm-server` be blank

**Comment by moorereason** [comment]
`tm-server` is blank because the `tomlStrFalse` TOML document doesn't match your data model.  Try using the Decoder in Strict mode, and you should see the problem.

**Comment by 60ke** [comment]
> ```go
> 	f, _ := os.Create("./test.toml")
>         defer f.Close()
> ```

Maybe I didn't express it clearly enough, I mean if encode order,may casue the root key move down，like 
```toml
tm-server = "127.0.0.1"
[[tm]]
  ip = "192.168.1.1"
```
if order,`toml-server` will move down,And then it doesn't mean what it meant。

**Comment by pelletier** [comment]
Just realized that you are using go-toml v1, which is not supported since April. go-toml v2 outputs this data structure correctly:

https://go.dev/play/p/MyG9A2t-HGc

**Comment by 60ke** [comment]
> Just realized that you are using go-toml v1, which is not supported since April. go-toml v2 outputs this data structure correctly:
> 
> https://go.dev/play/p/MyG9A2t-HGc

yes, go-toml v2 is ok, thanks for you reply
