### ISSUE TITLE
track path as well as location

### ISSUE THREAD

**Issue by nhooyr** [pelletier/go-toml#82]
For errors it would be useful to not only get the location of a field, but also a string for the path to it from the root. Something like `proxies[3].bind`. So that means index 3 of the proxies array or map and field bind. It's must more apparent than just the line and column number.

**Comment by pelletier** [comment]
Thanks! That's a good idea. Feel free to provide a patch if that's a pressing issue for you.

**Comment by pelletier** [comment]
Removing from the 1.0 milestone since I just realized that it does not change the interface of the functions, but rather just the content of the error message.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.

**Comment by fho** [comment]
I think it would be still very useful to have.
It would make it easy to include the path to a field for that e.g. a validation happens. This can be very useful especial in big toml files
