### ISSUE TITLE
Array of Tables not loaded propery

### ISSUE THREAD

**Issue by vladimirvivien** [pelletier/go-toml#83]
I ran across this issue where array of tables were not converted properly.
```
[[menu.main]]
a = menu1
b = menu 2
[[menu.main]]
c = menu 3
d = menu 4
```
Instead of getting a map with key main setup as follows:
`menu:map[main:[menu1, menu2, menu3, menu4]]`
I get a key main where its elements is collapsed to only the last two items:
`menu:map[main:[menu3, menu4]]`

The code is not returning a properly constructed slice when the array of tables items have the same key names.

**Comment by vladimirvivien** [comment]
@pelletier Hi, please see PR #84 .  It would be great if you could merge this soon as you can.  Thanks.

**Comment by pelletier** [comment]
Hi @vladimirvivien, thank you for your feedback!

I'm confused about the expectations here. According to [toml#array-of-tables](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md#array-of-tables), the following toml doc:

```toml
[[menu.main]]
a = "menu 1"
b = "menu 2"
[[menu.main]]
c = "menu 3"
d = "menu 4"
```

should produce the following tree:

```json
{
  "menu": {
    "main": [
      {"a": "menu 1", "b": "menu 2"},
      {"c": "menu 3", "d": "menu 4"}
    ]
  }
}
```

which is what is currently produced by go-toml.

Do you mind clarifying the issue and providing a failing test case? I'm sure we can get this fixed quickly :)

**Comment by vladimirvivien** [comment]
Hi @pelletier 
Thanks for the quick reply. The problem I ran into is that example was producing:
```
{
  "menu": {
    "main": [
      {"c": "menu 3", "d": "menu 4"}
    ]
  }
}
```
Backstory: My team is trying to lobby `spf13` to adopt your toml api (due to better licensing for our use).  The problem came from the following sample from spf13/Hugo configuration.  It was failing where only the last menu set was being returned.  Also I didn't see a test case in parser_test.go for this exact usecase.

```
[[menu.main]]
    name = "Tutorials"
    identifier = "tutorials"
    pre = "<i class='fa fa-book'></i>"
    weight = -40
[[menu.main]]
    name = "Troubleshooting"
    identifier = "troubleshooting"
    pre = "<i class='fa fa-wrench'></i>"
    weight = -30
[[menu.main]]
    name = "Tools"
    url = "/tools/"
    pre = "<i class='fa fa-cogs'></i>"
    weight = -25
[[menu.main]]
    name = "Hugo Cmd Reference"
    identifier = "commands"
    pre = "<i class='fa fa-space-shuttle'></i>"
    weight = -20
    url = "/commands/"
```

**Comment by pelletier** [comment]
Thanks for the detailed explanation @vladimirvivien! I misunderstood what you meant in the first place.

It was indeed a bug. I added a unit test to your pull request and merged the fix: https://github.com/pelletier/go-toml/commit/06484b677b85a7aeb4e833c39e529e5b9fb58ab2. Should be all good now.

Thank you very much for your contribution! Let me know if there is anything I can do to make the the transition easier for the Viper team.

**Comment by vladimirvivien** [comment]
@pelletier Awesome!!
Thanks for the quick turnaround.  By the way killer code and love the heavy lean on testing all things.  Made it simple to follow the code and pin down the bug.
