### ISSUE TITLE
Cannot decode integers into floats

### ISSUE THREAD

**Issue by horgh** [pelletier/go-toml#835]
**Describe the bug**
I have a config with entries like

```toml
foo = 5
```

And I would like to decode them into a `float64`. This errors with: `toml: cannot decode TOML integer into struct field main.conf.Foo of type float64`

**To Reproduce**
```go
package main

import (
        "log"

        toml "github.com/pelletier/go-toml/v2"
)

func main() {
        type conf struct {
                Foo float64 `json:"foo"`
        }
        var c conf

        buf := []byte(`foo = 5`)

        if err := toml.Unmarshal(buf, &c); err != nil {
                log.Fatal(err)
        }
        log.Printf("%+v", c)
}
```

**Expected behavior**
I think it would be good to be able to deserialize ints into floats. `encoding/json` works that way for instance.

**Versions**
 - go-toml: github.com/pelletier/go-toml/v2 v2.0.6
 - go: go version go1.19.4 linux/amd64
 - operating system: Linux

**Additional context**
I could write the config values as 5.0 to get around this. However the same config is also used by a Perl parser, which has a different issue when expressing numbers as 5.0. It would be helpful in my case to be able to leave it as "5".

Thank you!

**Comment by pelletier** [comment]
This should be fixed as of https://github.com/pelletier/go-toml/commit/9f5726004ef124b8d3a4844c90c8700ba20d154e. Feel free to reopen if it doesn't solve your problem!

**Comment by horgh** [comment]
Thank you!
